/* Салхи: ахмад горимын нэмэлт яриа сэдвүүд (dialogs-more.js-ийн дараа ачаална) */
(function(){
  var D=window.DLG_MORE;if(!D)return;
  D.scenes.push(
    ["pharmacy","Эмийн санд","a friendly pharmacist helping an older customer choose medicine for a cold and explaining the dose clearly","senior"],
    ["grandchild","Ач зээтэйгээ ярих","a cheerful young grandchild chatting warmly with their grandparent about school, food and weekend plans","senior"],
    ["neighbor","Хөрштэйгөө ярих","a kind neighbour chatting about the weather, the market and family, and inviting the learner in for tea","senior"]
  );
  Object.assign(D.mn,{
    pharmacy:[["Сайн байна уу. Танд юугаар туслах вэ?","Надад ханиадны эм хэрэгтэй."],["Халуурч байна уу?","Үгүй, гэхдээ ханиалгаж байна."],["Өдөрт гурван удаа нэг ширхэг уугаарай.","Өдөрт гурван удаа. Хоолны өмнө үү, дараа юу?"],["Хоолны дараа, устай уугаарай.","Баярлалаа. Хэд вэ?"],["Үнэтэй биш. Түргэн эдгэрээрэй!","Маш их баярлалаа. Баяртай."]],
    grandchild:[["Сайн уу! Өнөөдөр яаж байна?","Сайн, баярлалаа. Чи яаж байна?"],["Би өнөөдөр сургуульд явсан. Шинэ дуу сурсан.","Гайхалтай. Надад дуулж өгөх үү?"],["Тэгье! Та үдийн хоолондоо юу идсэн бэ?","Би шөл, талх идсэн. Амттай байсан."],["Ням гарагт цэцэрлэгт хүрээлэн явж болох уу?","Мэдээж. Хамт алхъя."],["Би танд маш их хайртай!","Би ч бас чамд хайртай. Ням гарагт уулзъя."]],
    neighbor:[["Өглөөний мэнд! Өнөөдөр сайхан цаг агаар байна.","Тийм, нартай, дулаахан байна."],["Та зах руу явж байна уу?","Тийм, надад ногоо, талх хэрэгтэй."],["Гэр бүл тань сайн уу?","Сайн. Хүү маань ням гарагт ирнэ."],["Сайхан юм. Цай уух уу?","Тийм, баярлалаа. Сайхан байх болно."],["Орж ирээрэй. Цай бэлэн боллоо.","Найрсаг зочломтгойд баярлалаа."]]
  });
  var L={
    en:{
      pharmacy:[["Hello. How can I help you?","I need medicine for a cold."],["Do you have a fever?","No, but I have a cough."],["Take one tablet three times a day.","Three times a day. Before or after meals?"],["After meals, with water.","Thank you. How much is it?"],["It is not expensive. Get well soon!","Thank you very much. Goodbye."]],
      grandchild:[["Hello! How are you today?","I am fine, thank you. And you?"],["I went to school today. I learned a new song.","That is wonderful. Can you sing it for me?"],["Yes! What did you eat for lunch?","I ate soup and bread. It was delicious."],["Can we go to the park on Sunday?","Yes, of course. We can take a walk."],["I love you very much!","I love you too. See you on Sunday."]],
      neighbor:[["Good morning! Nice weather today.","Yes, it is sunny and warm."],["Are you going to the market?","Yes, I need vegetables and bread."],["How is your family?","They are well. My son visits on Sunday."],["That is nice. Would you like some tea?","Yes, please. That would be lovely."],["Come in. The tea is ready.","Thank you for your kindness."]]
    },
    zh:{
      pharmacy:[["你好，需要什么帮助？(Nǐ hǎo, xūyào shénme bāngzhù?)","我需要感冒药。(Wǒ xūyào gǎnmào yào.)"],["你发烧吗？(Nǐ fāshāo ma?)","不发烧，但是咳嗽。(Bù fāshāo, dànshì késou.)"],["每天吃三次，每次一片。(Měi tiān chī sān cì, měi cì yí piàn.)","一天三次。饭前还是饭后吃？(Yì tiān sān cì. Fàn qián háishi fàn hòu chī?)"],["饭后，用水送服。(Fàn hòu, yòng shuǐ sòngfú.)","谢谢。多少钱？(Xièxie. Duōshao qián?)"],["不贵。祝你早日康复！(Bú guì. Zhù nǐ zǎorì kāngfù!)","非常感谢，再见。(Fēicháng gǎnxiè, zàijiàn.)"]],
      grandchild:[["你好！你今天怎么样？(Nǐ hǎo! Nǐ jīntiān zěnmeyàng?)","我很好，谢谢。你呢？(Wǒ hěn hǎo, xièxie. Nǐ ne?)"],["我今天去学校了。我学了一首新歌。(Wǒ jīntiān qù xuéxiào le. Wǒ xué le yì shǒu xīn gē.)","太好了。你能唱给我听吗？(Tài hǎo le. Nǐ néng chàng gěi wǒ tīng ma?)"],["好的！你中午吃了什么？(Hǎo de! Nǐ zhōngwǔ chī le shénme?)","我吃了汤和面包，很好吃。(Wǒ chī le tāng hé miànbāo, hěn hǎochī.)"],["星期天我们可以去公园吗？(Xīngqītiān wǒmen kěyǐ qù gōngyuán ma?)","当然可以。我们一起散步。(Dāngrán kěyǐ. Wǒmen yìqǐ sànbù.)"],["我非常爱你！(Wǒ fēicháng ài nǐ!)","我也爱你。星期天见。(Wǒ yě ài nǐ. Xīngqītiān jiàn.)"]],
      neighbor:[["早上好！今天天气真好。(Zǎoshang hǎo! Jīntiān tiānqì zhēn hǎo.)","是啊，阳光明媚，很暖和。(Shì a, yángguāng míngmèi, hěn nuǎnhuo.)"],["您去市场吗？(Nín qù shìchǎng ma?)","对，我要买菜和面包。(Duì, wǒ yào mǎi cài hé miànbāo.)"],["您家人好吗？(Nín jiārén hǎo ma?)","都很好。我儿子星期天来看我。(Dōu hěn hǎo. Wǒ érzi xīngqītiān lái kàn wǒ.)"],["真好。您想喝茶吗？(Zhēn hǎo. Nín xiǎng hē chá ma?)","好的，谢谢，那太好了。(Hǎo de, xièxie, nà tài hǎo le.)"],["请进，茶已经泡好了。(Qǐng jìn, chá yǐjīng pào hǎo le.)","谢谢您的热情。(Xièxie nín de rèqíng.)"]]
    },
    ru:{
      pharmacy:[["Здравствуйте. Чем могу помочь?","Мне нужно лекарство от простуды."],["У вас температура?","Нет, но у меня кашель."],["Принимайте по одной таблетке три раза в день.","Три раза в день. До еды или после?"],["После еды, запивая водой.","Спасибо. Сколько это стоит?"],["Недорого. Выздоравливайте!","Большое спасибо. До свидания."]],
      grandchild:[["Здравствуйте! Как вы сегодня?","Хорошо, спасибо. А ты как?"],["Я сегодня был в школе. Выучил новую песню.","Замечательно. Споёшь мне её?"],["Да! Что вы ели на обед?","Я ел суп и хлеб. Было очень вкусно."],["Можно в воскресенье пойти в парк?","Конечно. Мы погуляем вместе."],["Я вас очень люблю!","И я тебя люблю. До воскресенья."]],
      neighbor:[["Доброе утро! Сегодня хорошая погода.","Да, солнечно и тепло."],["Вы идёте на рынок?","Да, мне нужны овощи и хлеб."],["Как ваша семья?","Все здоровы. Сын приедет в воскресенье."],["Как хорошо. Хотите чаю?","Да, пожалуйста. Это было бы чудесно."],["Проходите. Чай готов.","Спасибо за ваше гостеприимство."]]
    },
    de:{
      pharmacy:[["Guten Tag. Wie kann ich Ihnen helfen?","Ich brauche ein Medikament gegen Erkältung."],["Haben Sie Fieber?","Nein, aber ich habe Husten."],["Nehmen Sie dreimal täglich eine Tablette.","Dreimal täglich. Vor oder nach dem Essen?"],["Nach dem Essen, mit Wasser.","Danke. Was kostet das?"],["Das ist nicht teuer. Gute Besserung!","Vielen Dank. Auf Wiedersehen."]],
      grandchild:[["Hallo! Wie geht es dir heute?","Mir geht es gut, danke. Und dir?"],["Ich war heute in der Schule. Ich habe ein neues Lied gelernt.","Wunderbar. Singst du es mir vor?"],["Ja! Was hast du zu Mittag gegessen?","Ich habe Suppe und Brot gegessen. Es war lecker."],["Können wir am Sonntag in den Park gehen?","Natürlich. Wir machen einen Spaziergang."],["Ich hab dich sehr lieb!","Ich hab dich auch lieb. Bis Sonntag."]],
      neighbor:[["Guten Morgen! Schönes Wetter heute.","Ja, es ist sonnig und warm."],["Gehen Sie zum Markt?","Ja, ich brauche Gemüse und Brot."],["Wie geht es Ihrer Familie?","Gut. Mein Sohn besucht mich am Sonntag."],["Das ist schön. Möchten Sie Tee?","Ja, gern. Das wäre wunderbar."],["Kommen Sie herein. Der Tee ist fertig.","Danke für Ihre Freundlichkeit."]]
    },
    ja:{
      pharmacy:[["こんにちは。どうなさいましたか。(Konnichiwa. Dō nasaimashita ka.)","かぜのくすりがほしいです。(Kaze no kusuri ga hoshii desu.)"],["ねつはありますか。(Netsu wa arimasu ka.)","いいえ、でもせきが出ます。(Iie, demo seki ga demasu.)"],["一日三回、一つぶのんでください。(Ichinichi sankai, hitotsubu nonde kudasai.)","一日三回ですね。しょくぜんですか、しょくごですか。(Ichinichi sankai desu ne. Shokuzen desu ka, shokugo desu ka.)"],["しょくごに、水でのんでください。(Shokugo ni, mizu de nonde kudasai.)","ありがとうございます。いくらですか。(Arigatō gozaimasu. Ikura desu ka.)"],["高くありません。おだいじに。(Takaku arimasen. Odaijini.)","どうもありがとうございました。さようなら。(Dōmo arigatō gozaimashita. Sayōnara.)"]],
      grandchild:[["こんにちは。きょうはげんきですか。(Konnichiwa. Kyō wa genki desu ka.)","はい、げんきです。あなたは。(Hai, genki desu. Anata wa.)"],["きょう、学校へ行きました。あたらしい歌をならいました。(Kyō, gakkō e ikimashita. Atarashii uta o naraimashita.)","すばらしいですね。うたってくれますか。(Subarashii desu ne. Utatte kuremasu ka.)"],["はい！おひるごはんに何をたべましたか。(Hai! Ohirugohan ni nani o tabemashita ka.)","スープとパンをたべました。おいしかったです。(Sūpu to pan o tabemashita. Oishikatta desu.)"],["にちようびに、こうえんへ行ってもいいですか。(Nichiyōbi ni, kōen e itte mo ii desu ka.)","もちろんです。いっしょにさんぽしましょう。(Mochiron desu. Issho ni sanpo shimashō.)"],["だいすきです！(Daisuki desu!)","わたしもだいすきです。にちようびに会いましょう。(Watashi mo daisuki desu. Nichiyōbi ni aimashō.)"]],
      neighbor:[["おはようございます。きょうはいいお天気ですね。(Ohayō gozaimasu. Kyō wa ii otenki desu ne.)","ええ、はれて、あたたかいですね。(Ee, harete, atatakai desu ne.)"],["いちばへ行きますか。(Ichiba e ikimasu ka.)","はい、やさいとパンがひつようです。(Hai, yasai to pan ga hitsuyō desu.)"],["ごかぞくはお元気ですか。(Gokazoku wa ogenki desu ka.)","みんな元気です。むすこが日曜日に来ます。(Minna genki desu. Musuko ga nichiyōbi ni kimasu.)"],["いいですね。おちゃはいかがですか。(Ii desu ne. Ocha wa ikaga desu ka.)","はい、いただきます。うれしいです。(Hai, itadakimasu. Ureshii desu.)"],["どうぞ、おあがりください。おちゃができました。(Dōzo, oagari kudasai. Ocha ga dekimashita.)","ごしんせつにありがとうございます。(Goshinsetsu ni arigatō gozaimasu.)"]]
    },
    ko:{
      pharmacy:[["안녕하세요. 무엇을 도와드릴까요? (Annyeonghaseyo. Mueoseul dowadeurilkkayo?)","감기약이 필요해요. (Gamgiyagi piryohaeyo.)"],["열이 있으세요? (Yeori isseuseyo?)","아니요, 하지만 기침이 나요. (Aniyo, hajiman gichimi nayo.)"],["하루에 세 번, 한 알씩 드세요. (Harue se beon, han alssik deuseyo.)","하루에 세 번이요. 식전이에요, 식후예요? (Harue se beoniyo. Sikjeonieyo, sikhuyeyo?)"],["식후에 물과 함께 드세요. (Sikhue mulgwa hamkke deuseyo.)","감사합니다. 얼마예요? (Gamsahamnida. Eolmayeyo?)"],["비싸지 않아요. 빨리 나으세요! (Bissaji anayo. Ppalli naeuseyo!)","정말 감사합니다. 안녕히 계세요. (Jeongmal gamsahamnida. Annyeonghi gyeseyo.)"]],
      grandchild:[["안녕하세요! 오늘 어떠세요? (Annyeonghaseyo! Oneul eotteoseyo?)","잘 지내요, 고마워요. 너는? (Jal jinaeyo, gomawoyo. Neoneun?)"],["오늘 학교에 갔어요. 새 노래를 배웠어요. (Oneul hakgyoe gasseoyo. Sae noraereul baewosseoyo.)","멋지구나. 나한테 불러 줄래? (Meotjiguna. Nahante bulleo jullae?)"],["네! 점심에 뭘 드셨어요? (Ne! Jeomsime mwol deusyeosseoyo?)","수프와 빵을 먹었어요. 맛있었어요. (Supeuwa ppangeul meogeosseoyo. Masisseosseoyo.)"],["일요일에 공원에 가도 돼요? (Iryoire gongwone gado dwaeyo?)","물론이지. 같이 산책하자. (Mullonyiji. Gachi sanchaekhaja.)"],["정말 사랑해요! (Jeongmal saranghaeyo!)","나도 사랑해. 일요일에 보자. (Nado saranghae. Iryoire boja.)"]],
      neighbor:[["안녕하세요! 오늘 날씨가 좋네요. (Annyeonghaseyo! Oneul nalssiga jonneyo.)","네, 맑고 따뜻해요. (Ne, malkgo ttatteuthaeyo.)"],["시장에 가세요? (Sijange gaseyo?)","네, 채소와 빵이 필요해요. (Ne, chaesowa ppangi piryohaeyo.)"],["가족은 잘 지내세요? (Gajogeun jal jinaeseyo?)","다들 잘 지내요. 아들이 일요일에 와요. (Dadeul jal jinaeyo. Adeuri iryoire wayo.)"],["좋네요. 차 한잔 하실래요? (Jonneyo. Cha hanjan hasillaeyo?)","네, 좋아요. 정말 좋겠어요. (Ne, joayo. Jeongmal jokesseoyo.)"],["들어오세요. 차가 준비됐어요. (Deureooseyo. Chaga junbidwaesseoyo.)","친절에 감사드려요. (Chinjeore gamsadeuryeoyo.)"]]
    }
  };
  Object.keys(L).forEach(function(l){D.lines[l]=D.lines[l]||{};Object.assign(D.lines[l],L[l]);});
})();
