/* Салхи: сонсох ба ярих хэсгийн нэмэлт сэдвүүд (6 хэл) */
window.DLG_MORE={
scenes:[
["shop","Дэлгүүрт хувцас авах","a friendly shop assistant helping the learner buy a jacket, asking about size and fit","adult"],
["restaurant","Ресторанд","a polite waiter at a restaurant taking the learner's order","adult"],
["directions","Зам асуух","a helpful local person giving the learner walking directions to the station","adult"],
["doctor","Эмчид үзүүлэх","a kind doctor asking the learner about a headache and giving advice","adult"],
["airport","Нисэх буудал дээр","an airport check-in agent helping the learner check in for a flight","adult"],
["taxi","Таксинд","a taxi driver taking the learner to the airport","adult"]
],
mn:{
shop:[["Танд туслах уу?","Би хүрэм хайж байна."],["Ямар размер өмсдөг вэ?","Дунд размер өгөөч."],["Өмсөж үзэх үү?","Тийм, өмсөж үзэх өрөө хаана вэ?"],["Яаж таарч байна?","Жаахан том байна."],["Жижиг нь хэрэгтэй юу?","Тийм, тэгээд авна."]],
restaurant:[["Хэдэн хүний ширээ вэ?","Хоёр хүний ширээ өгөөч."],["Захиалга өгөхөд бэлэн үү?","Тийм, шөл авъя."],["Уух юм авах уу?","Ус өгөөч."],["Хоол ямар байна?","Маш амттай."],["Тооцоо авах уу?","Тийм, өгнө үү."]],
directions:[["Уучлаарай, хаашаа явах гэж байна?","Буудал руу явах гэж байна."],["Хоёр байшин чигээрээ яв.","За, дараа нь?"],["Банкны дэргэд зүүн тийш эргэ.","Банкны дэргэд зүүн тийш. Хол уу?"],["Үгүй, алхвал таван минут.","Гайхалтай, маш их баярлалаа."],["Зүгээр. Өдрийг сайхан өнгөрүүлээрэй!","Та ч бас. Баяртай!"]],
doctor:[["Сайн байна уу. Юу болоод байна?","Миний толгой өвдөж байна."],["Хэр удаан өвдөж байна?","Өчигдрөөс хойш."],["Халуурч байна уу?","Тийм, бага зэрэг."],["Энэ эмийг өдөрт хоёр удаа уугаарай.","Өдөрт хоёр удаа. Ойлголоо."],["Амарч, ус уугаарай.","Баярлалаа, эмч ээ."]],
airport:[["Өглөөний мэнд. Паспортоо өгнө үү.","Иймээ."],["Хаашаа нисэх вэ?","Сөүл рүү нисэнэ."],["Ачаа тээш байгаа юу?","Тийм, нэг чемодан."],["Цонхны хажуугийн уу, гарц талын суудал уу?","Цонхны хажуугийнх байг."],["Энэ таны тасалбар. Хаалга тавдугаар.","Баярлалаа. Тавдугаар хаалга хаана вэ?"]],
taxi:[["Хаашаа?","Нисэх буудал руу."],["Ачаа байгаа юу?","Тийм, хоёр цүнх."],["Ойролцоогоор гучин минут болно.","За. Болгоомжтой жолоодоорой."],["Яаж төлөх вэ?","Картаар төлье."],["Баярлалаа. Аяллаа сайхан өнгөрүүлээрэй!","Баярлалаа. Баяртай!"]]
},
lines:{
en:{
shop:[["Hello! Can I help you?","I am looking for a jacket."],["What size do you wear?","Medium, please."],["Would you like to try it on?","Yes, where is the fitting room?"],["How does it fit?","It is a little big."],["Would you like a smaller one?","Yes, and I will take it."]],
restaurant:[["Welcome! Table for how many?","Table for two, please."],["Are you ready to order?","Yes, I would like the soup."],["Anything to drink?","Water, please."],["How is the food?","It is delicious."],["Would you like the bill?","Yes, please."]],
directions:[["Excuse me, where are you going?","I am going to the station."],["Go straight for two blocks.","Okay, and then?"],["Turn left at the bank.","Turn left at the bank. Is it far?"],["No, it takes five minutes on foot.","Great, thank you very much."],["You are welcome. Have a nice day!","You too. Goodbye!"]],
doctor:[["Hello. What is the problem?","I have a headache."],["How long have you had it?","Since yesterday."],["Do you have a fever?","Yes, a little."],["Take this medicine twice a day.","Twice a day. I understand."],["Rest and drink water.","Thank you, doctor."]],
airport:[["Good morning. Passport, please.","Here you are."],["Where are you flying to?","I am flying to Seoul."],["Do you have any luggage?","Yes, one suitcase."],["Would you like a window or an aisle seat?","A window seat, please."],["Here is your ticket. The gate is number five.","Thank you. Where is gate five?"]],
taxi:[["Where to?","To the airport, please."],["Do you have any luggage?","Yes, two bags."],["It takes about thirty minutes.","Okay. Please drive carefully."],["How would you like to pay?","By card, please."],["Thank you. Have a good trip!","Thank you. Goodbye!"]]
},
zh:{
shop:[["你好！需要帮忙吗？(Nǐ hǎo! Xūyào bāngmáng ma?)","我想买一件外套。(Wǒ xiǎng mǎi yí jiàn wàitào.)"],["你穿多大号的？(Nǐ chuān duō dà hào de?)","请给我中号。(Qǐng gěi wǒ zhōng hào.)"],["要试一下吗？(Yào shì yíxià ma?)","好的，试衣间在哪儿？(Hǎo de, shìyījiān zài nǎr?)"],["合适吗？(Héshì ma?)","有一点大。(Yǒu yìdiǎn dà.)"],["要小一点的吗？(Yào xiǎo yìdiǎn de ma?)","要，我就买这件。(Yào, wǒ jiù mǎi zhè jiàn.)"]],
restaurant:[["欢迎光临！几位？(Huānyíng guānglín! Jǐ wèi?)","两位。(Liǎng wèi.)"],["可以点菜了吗？(Kěyǐ diǎn cài le ma?)","可以，我要汤。(Kěyǐ, wǒ yào tāng.)"],["喝点什么？(Hē diǎn shénme?)","请给我水。(Qǐng gěi wǒ shuǐ.)"],["菜怎么样？(Cài zěnmeyàng?)","非常好吃。(Fēicháng hǎochī.)"],["要买单吗？(Yào mǎidān ma?)","好的，谢谢。(Hǎo de, xièxie.)"]],
directions:[["请问，您要去哪儿？(Qǐngwèn, nín yào qù nǎr?)","我要去车站。(Wǒ yào qù chēzhàn.)"],["一直走两个路口。(Yìzhí zǒu liǎng ge lùkǒu.)","好的，然后呢？(Hǎo de, ránhòu ne?)"],["在银行那儿往左拐。(Zài yínháng nàr wǎng zuǒ guǎi.)","在银行往左拐。远吗？(Zài yínháng wǎng zuǒ guǎi. Yuǎn ma?)"],["不远，走路五分钟。(Bù yuǎn, zǒulù wǔ fēnzhōng.)","太好了，非常感谢。(Tài hǎo le, fēicháng gǎnxiè.)"],["不客气。祝你有美好的一天！(Bú kèqi. Zhù nǐ yǒu měihǎo de yì tiān!)","你也是。再见！(Nǐ yě shì. Zàijiàn!)"]],
doctor:[["你好。哪儿不舒服？(Nǐ hǎo. Nǎr bù shūfu?)","我头疼。(Wǒ tóu téng.)"],["疼多久了？(Téng duō jiǔ le?)","从昨天开始。(Cóng zuótiān kāishǐ.)"],["发烧吗？(Fāshāo ma?)","有一点。(Yǒu yìdiǎn.)"],["这个药一天吃两次。(Zhège yào yì tiān chī liǎng cì.)","一天两次，我明白了。(Yì tiān liǎng cì, wǒ míngbai le.)"],["多休息，多喝水。(Duō xiūxi, duō hē shuǐ.)","谢谢医生。(Xièxie yīshēng.)"]],
airport:[["早上好。请给我护照。(Zǎoshang hǎo. Qǐng gěi wǒ hùzhào.)","给您。(Gěi nín.)"],["您飞往哪里？(Nín fēi wǎng nǎlǐ?)","我飞往首尔。(Wǒ fēi wǎng Shǒu'ěr.)"],["有行李吗？(Yǒu xíngli ma?)","有，一个箱子。(Yǒu, yí ge xiāngzi.)"],["您要靠窗还是靠过道？(Nín yào kào chuāng háishi kào guòdào?)","请给我靠窗的。(Qǐng gěi wǒ kào chuāng de.)"],["这是您的票，五号登机口。(Zhè shì nín de piào, wǔ hào dēngjīkǒu.)","谢谢。五号登机口在哪儿？(Xièxie. Wǔ hào dēngjīkǒu zài nǎr?)"]],
taxi:[["去哪儿？(Qù nǎr?)","请去机场。(Qǐng qù jīchǎng.)"],["有行李吗？(Yǒu xíngli ma?)","有，两个包。(Yǒu, liǎng ge bāo.)"],["大概三十分钟。(Dàgài sānshí fēnzhōng.)","好的，请慢点开。(Hǎo de, qǐng màn diǎn kāi.)"],["怎么付款？(Zěnme fùkuǎn?)","刷卡。(Shuā kǎ.)"],["谢谢。旅途愉快！(Xièxie. Lǚtú yúkuài!)","谢谢，再见！(Xièxie, zàijiàn!)"]]
},
ru:{
shop:[["Здравствуйте! Вам помочь?","Я ищу куртку."],["Какой у вас размер?","Средний, пожалуйста."],["Хотите примерить?","Да, где примерочная?"],["Как сидит?","Немного великовата."],["Хотите поменьше?","Да, и я её возьму."]],
restaurant:[["Добро пожаловать! На сколько человек?","На двоих, пожалуйста."],["Вы готовы сделать заказ?","Да, я хочу суп."],["Что будете пить?","Воду, пожалуйста."],["Как вам еда?","Очень вкусно."],["Хотите счёт?","Да, пожалуйста."]],
directions:[["Извините, куда вы идёте?","Я иду на вокзал."],["Идите прямо два квартала.","Хорошо, а потом?"],["У банка поверните налево.","У банка налево. Это далеко?"],["Нет, пять минут пешком.","Отлично, большое спасибо."],["Пожалуйста. Хорошего дня!","И вам. До свидания!"]],
doctor:[["Здравствуйте. Что вас беспокоит?","У меня болит голова."],["Как давно?","С вчерашнего дня."],["У вас температура?","Да, небольшая."],["Принимайте это лекарство два раза в день.","Два раза в день. Я понял."],["Отдыхайте и пейте воду.","Спасибо, доктор."]],
airport:[["Доброе утро. Паспорт, пожалуйста.","Вот, пожалуйста."],["Куда вы летите?","Я лечу в Сеул."],["У вас есть багаж?","Да, один чемодан."],["Вам место у окна или у прохода?","Место у окна, пожалуйста."],["Вот ваш билет. Выход номер пять.","Спасибо. Где выход номер пять?"]],
taxi:[["Куда едем?","В аэропорт, пожалуйста."],["У вас есть багаж?","Да, две сумки."],["Езды около тридцати минут.","Хорошо. Езжайте осторожно, пожалуйста."],["Как будете платить?","Картой, пожалуйста."],["Спасибо. Счастливого пути!","Спасибо. До свидания!"]]
},
de:{
shop:[["Guten Tag! Kann ich Ihnen helfen?","Ich suche eine Jacke."],["Welche Größe tragen Sie?","Mittel, bitte."],["Möchten Sie sie anprobieren?","Ja, wo ist die Umkleidekabine?"],["Wie passt sie?","Sie ist ein bisschen groß."],["Möchten Sie eine kleinere?","Ja, und ich nehme sie."]],
restaurant:[["Willkommen! Für wie viele Personen?","Für zwei Personen, bitte."],["Sind Sie bereit zu bestellen?","Ja, ich möchte die Suppe."],["Was möchten Sie trinken?","Wasser, bitte."],["Wie schmeckt das Essen?","Es ist köstlich."],["Möchten Sie die Rechnung?","Ja, bitte."]],
directions:[["Entschuldigung, wohin möchten Sie?","Ich möchte zum Bahnhof."],["Gehen Sie zwei Blocks geradeaus.","Okay, und dann?"],["Biegen Sie bei der Bank links ab.","Bei der Bank links. Ist es weit?"],["Nein, zu Fuß fünf Minuten.","Prima, vielen Dank."],["Gern geschehen. Einen schönen Tag!","Ihnen auch. Auf Wiedersehen!"]],
doctor:[["Guten Tag. Was fehlt Ihnen?","Ich habe Kopfschmerzen."],["Seit wann haben Sie sie?","Seit gestern."],["Haben Sie Fieber?","Ja, ein bisschen."],["Nehmen Sie diese Tablette zweimal am Tag.","Zweimal am Tag. Ich verstehe."],["Ruhen Sie sich aus und trinken Sie Wasser.","Danke, Herr Doktor."]],
airport:[["Guten Morgen. Ihren Reisepass, bitte.","Bitte sehr."],["Wohin fliegen Sie?","Ich fliege nach Seoul."],["Haben Sie Gepäck?","Ja, einen Koffer."],["Möchten Sie einen Fensterplatz oder einen Gangplatz?","Einen Fensterplatz, bitte."],["Hier ist Ihr Ticket. Der Flugsteig ist die Nummer fünf.","Danke. Wo ist Flugsteig fünf?"]],
taxi:[["Wohin soll es gehen?","Zum Flughafen, bitte."],["Haben Sie Gepäck?","Ja, zwei Taschen."],["Die Fahrt dauert etwa dreißig Minuten.","Okay. Fahren Sie bitte vorsichtig."],["Wie möchten Sie bezahlen?","Mit Karte, bitte."],["Danke. Gute Reise!","Danke. Auf Wiedersehen!"]]
},
ja:{
shop:[["いらっしゃいませ。何かお探しですか。(Irasshaimase. Nanika osagashi desu ka.)","ジャケットを探しています。(Jaketto o sagashite imasu.)"],["サイズはいくつですか。(Saizu wa ikutsu desu ka.)","Mサイズをください。(M saizu o kudasai.)"],["試着しますか。(Shichaku shimasu ka.)","はい、試着室はどこですか。(Hai, shichakushitsu wa doko desu ka.)"],["どうですか。(Dou desu ka.)","少し大きいです。(Sukoshi ookii desu.)"],["もっと小さいのがいいですか。(Motto chiisai no ga ii desu ka.)","はい、それを買います。(Hai, sore o kaimasu.)"]],
restaurant:[["いらっしゃいませ。何名様ですか。(Irasshaimase. Nanmeisama desu ka.)","二人です。(Futari desu.)"],["ご注文はお決まりですか。(Gochuumon wa okimari desu ka.)","はい、スープをください。(Hai, suupu o kudasai.)"],["お飲み物は。(Onomimono wa.)","お水をください。(Omizu o kudasai.)"],["お味はいかがですか。(Oaji wa ikaga desu ka.)","とてもおいしいです。(Totemo oishii desu.)"],["お会計をしますか。(Okaikei o shimasu ka.)","はい、お願いします。(Hai, onegaishimasu.)"]],
directions:[["すみません、どこへ行きますか。(Sumimasen, doko e ikimasu ka.)","駅へ行きます。(Eki e ikimasu.)"],["二つ目の角までまっすぐ行ってください。(Futatsume no kado made massugu itte kudasai.)","はい、それから？(Hai, sorekara?)"],["銀行のところを左に曲がってください。(Ginkou no tokoro o hidari ni magatte kudasai.)","銀行を左ですね。遠いですか。(Ginkou o hidari desu ne. Tooi desu ka.)"],["いいえ、歩いて五分です。(Iie, aruite gofun desu.)","よかった。ありがとうございます。(Yokatta. Arigatou gozaimasu.)"],["どういたしまして。よい一日を！(Dou itashimashite. Yoi ichinichi o!)","あなたもね。さようなら。(Anata mo ne. Sayounara.)"]],
doctor:[["こんにちは。どうしましたか。(Konnichiwa. Dou shimashita ka.)","頭が痛いです。(Atama ga itai desu.)"],["いつからですか。(Itsu kara desu ka.)","昨日からです。(Kinou kara desu.)"],["熱はありますか。(Netsu wa arimasu ka.)","はい、少しあります。(Hai, sukoshi arimasu.)"],["この薬を一日二回飲んでください。(Kono kusuri o ichinichi nikai nonde kudasai.)","一日二回ですね。分かりました。(Ichinichi nikai desu ne. Wakarimashita.)"],["ゆっくり休んで、水を飲んでください。(Yukkuri yasunde, mizu o nonde kudasai.)","ありがとうございました。(Arigatou gozaimashita.)"]],
airport:[["おはようございます。パスポートをお願いします。(Ohayou gozaimasu. Pasupooto o onegaishimasu.)","はい、どうぞ。(Hai, douzo.)"],["どちらまで行きますか。(Dochira made ikimasu ka.)","ソウルまで行きます。(Souru made ikimasu.)"],["お荷物はありますか。(Onimotsu wa arimasu ka.)","はい、スーツケースが一つです。(Hai, suutsukeesu ga hitotsu desu.)"],["窓側と通路側、どちらがいいですか。(Madogawa to tsuurogawa, dochira ga ii desu ka.)","窓側をお願いします。(Madogawa o onegaishimasu.)"],["こちらがチケットです。搭乗口は五番です。(Kochira ga chiketto desu. Toujouguchi wa goban desu.)","ありがとうございます。五番はどこですか。(Arigatou gozaimasu. Goban wa doko desu ka.)"]],
taxi:[["どちらまでですか。(Dochira made desu ka.)","空港までお願いします。(Kuukou made onegaishimasu.)"],["お荷物はありますか。(Onimotsu wa arimasu ka.)","はい、かばんが二つです。(Hai, kaban ga futatsu desu.)"],["三十分くらいかかります。(Sanjuppun kurai kakarimasu.)","分かりました。安全運転でお願いします。(Wakarimashita. Anzen unten de onegaishimasu.)"],["お支払いはどうしますか。(Oshiharai wa dou shimasu ka.)","カードでお願いします。(Kaado de onegaishimasu.)"],["ありがとうございます。よい旅を！(Arigatou gozaimasu. Yoi tabi o!)","ありがとう。さようなら。(Arigatou. Sayounara.)"]]
},
ko:{
shop:[["어서 오세요. 도와드릴까요? (Eoseo oseyo. Dowadeurilkkayo?)","재킷을 찾고 있어요. (Jaekiseul chatgo isseoyo.)"],["사이즈가 어떻게 되세요? (Saijeuga eotteoke doeseyo?)","중간 사이즈로 주세요. (Junggan saijeuro juseyo.)"],["입어 보시겠어요? (Ibeo bosigesseoyo?)","네, 탈의실이 어디예요? (Ne, taruisiri eodiyeyo?)"],["어떠세요? (Eotteoseyo?)","조금 커요. (Jogeum keoyo.)"],["더 작은 걸로 드릴까요? (Deo jageun geollo deurilkkayo?)","네, 그걸로 살게요. (Ne, geugeollo salgeyo.)"]],
restaurant:[["어서 오세요. 몇 분이세요? (Eoseo oseyo. Myeot buniseyo?)","두 명이에요. (Du myeongieyo.)"],["주문하시겠어요? (Jumunhasigesseoyo?)","네, 국을 주세요. (Ne, gugeul juseyo.)"],["마실 것은요? (Masil geoseunyo?)","물을 주세요. (Mureul juseyo.)"],["음식은 어떠세요? (Eumsigeun eotteoseyo?)","정말 맛있어요. (Jeongmal masisseoyo.)"],["계산해 드릴까요? (Gyesanhae deurilkkayo?)","네, 부탁해요. (Ne, butakaeyo.)"]],
directions:[["실례합니다. 어디에 가세요? (Sillyehamnida. Eodie gaseyo?)","역에 가요. (Yeoge gayo.)"],["두 블록 쭉 가세요. (Du beullok jjuk gaseyo.)","네, 그다음은요? (Ne, geudaeumeunyo?)"],["은행에서 왼쪽으로 가세요. (Eunhaengeseo oenjjogeuro gaseyo.)","은행에서 왼쪽이요. 멀어요? (Eunhaengeseo oenjjogiyo. Meoreoyo?)"],["아니요, 걸어서 오 분이에요. (Aniyo, georeoseo o buniyeyo.)","잘됐네요. 정말 감사합니다. (Jaldwaetneyo. Jeongmal gamsahamnida.)"],["천만에요. 좋은 하루 되세요! (Cheonmaneyo. Joeun haru doeseyo!)","당신도요. 안녕히 가세요! (Dangsindoyo. Annyeonghi gaseyo!)"]],
doctor:[["안녕하세요. 어디가 아프세요? (Annyeonghaseyo. Eodiga apeuseyo?)","머리가 아파요. (Meoriga apayo.)"],["언제부터 아팠어요? (Eonjebuteo apasseoyo?)","어제부터요. (Eojebuteoyo.)"],["열이 있어요? (Yeori isseoyo?)","네, 조금요. (Ne, jogeumyo.)"],["이 약을 하루에 두 번 드세요. (I yageul harue du beon deuseyo.)","하루에 두 번이요. 알겠어요. (Harue du beoniyo. Algesseoyo.)"],["푹 쉬고 물을 많이 드세요. (Puk swigo mureul mani deuseyo.)","감사합니다, 선생님. (Gamsahamnida, seonsaengnim.)"]],
airport:[["안녕하세요. 여권을 주세요. (Annyeonghaseyo. Yeogwoneul juseyo.)","여기 있어요. (Yeogi isseoyo.)"],["어디로 가세요? (Eodiro gaseyo?)","서울로 가요. (Seoullo gayo.)"],["짐이 있으세요? (Jimi isseuseyo?)","네, 가방이 하나예요. (Ne, gabangi hanayeyo.)"],["창가 좌석과 복도 좌석 중 어느 걸로 하시겠어요? (Changga jwaseokgwa bokdo jwaseok jung eoneu geollo hasigesseoyo?)","창가로 주세요. (Changgaro juseyo.)"],["여기 표예요. 탑승구는 오 번이에요. (Yeogi pyoyeyo. Tapseunggunun o beonieyo.)","감사합니다. 오 번 탑승구는 어디예요? (Gamsahamnida. O beon tapseunggunun eodiyeyo?)"]],
taxi:[["어디로 갈까요? (Eodiro galkkayo?)","공항으로 가 주세요. (Gonghangeuro ga juseyo.)"],["짐이 있으세요? (Jimi isseuseyo?)","네, 가방 두 개요. (Ne, gabang du gaeyo.)"],["삼십 분쯤 걸려요. (Samsip bunjjeum geollyeoyo.)","알겠어요. 안전하게 가 주세요. (Algesseoyo. Anjeonhage ga juseyo.)"],["어떻게 결제하시겠어요? (Eotteoke gyeoljehasigesseoyo?)","카드로 할게요. (Kadeuro halgeyo.)"],["감사합니다. 좋은 여행 되세요! (Gamsahamnida. Joeun yeohaeng doeseyo!)","감사합니다. 안녕히 가세요! (Gamsahamnida. Annyeonghi gaseyo!)"]]
}
}
};
