(window.LP=window.LP||[]).push(["en",4,`
b1|when ба while: тасалдсан үйл|Урт үргэлжилсэн үйлд Past Continuous, түүнийг тасалсан богино үйлд Past Simple: I was cooking when the phone rang.¶while + Past Continuous: While I was cooking, the phone rang. when + Past Simple.|while + Past Continuous · when + Past Simple|I was cooking when the phone rang.|Намайг хоол хийж байхад утас дуугарсан.|While she was walking home, it started to rain.|Түүнийг гэр лүүгээ алхаж байхад бороо орж эхэлсэн.|We were watching TV when the lights went out.|Биднийг зурагт үзэж байхад гэрэл унтарсан.|He broke his leg while he was skiing.|Тэр цанаар гулгаж байхдаа хөлөө хугалсан.|I was cooking when the phone ___.|rang~was ringing~rings|___ she was walking home, it started to rain.|While~When~During|He broke his leg while he ___.|was skiing~skied~skis
b1|Ирээдүйн гурван хэлбэр: will, going to, Present Continuous|will — шуурхай шийдвэр, таамаг: I'll answer it. going to — урьдчилсан төлөвлөгөө, нотолгоотой таамаг: I'm going to study law. Present Continuous — товлосон уулзалт: I'm meeting Tom at 6.|will (шийдвэр, таамаг) · going to (төлөвлөгөө) · am / is / are + V-ing (товлолт)|The phone is ringing. I'll answer it.|Утас дуугарч байна. Би авъя.|I'm going to study law next year.|Би ирэх жил хууль сурахаар төлөвлөж байна.|I'm meeting Tom at six tonight.|Би өнөө орой зургаан цагт Томтой уулзана.|Look at the clouds! It's going to rain.|Үүл хар! Бороо орох нь.|The phone is ringing. I ___ it.|'ll answer~'m going to answer~answer|Look at the clouds! It ___ rain.|'s going to~will to~is|I ___ Tom at six tonight. (товлосон)|'m meeting~meet~will meeting
b1|as soon as, before, after + Present|Ирээдүйн цагийн өгүүлбэрт when, as soon as, before, after, until-ийн дараа Present Simple (will биш): I'll call you as soon as I arrive.|as soon as / when / before / after / until + Present, ... will ...|I'll call you as soon as I arrive.|Ирэнгүүтээ чам руу залгана.|We'll have dinner after the guests leave.|Зочид явсны дараа бид оройн хоол идэнэ.|Don't go until I come back.|Намайг ирэх хүртэл битгий яв.|Before you leave, turn off the lights.|Гарахаасаа өмнө гэрлээ унтраа.|I'll call you as soon as I ___.|arrive~will arrive~arrived|Don't go until I ___ back.|come~will come~came|We'll have dinner after the guests ___.|leave~will leave~leaving
b1|If I were you: зөвлөгөө|Зөвлөгөө өгөхдөө If I were you, I would / I'd + V. Бүх биед were: If I were you (was ч ярианд сонсогддог).|If I were you, I'd + V|If I were you, I'd see a doctor.|Би чиний оронд байсан бол эмчид үзүүлнэ.|If I were you, I wouldn't buy it.|Би чиний оронд бол үүнийг авахгүй.|If I were you, I'd apologise.|Би чиний оронд бол уучлалт гуйна.|What would you do if you were me?|Чи миний оронд байсан бол юу хийх байсан бэ?|If I ___ you, I'd see a doctor.|were~am~will be|If I were you, I ___ buy it.|wouldn't~won't~don't|What would you do if you ___ me?|were~are~will be
b1|unless|unless = if ... not — «хэрэв ... -гүй бол»: You won't pass unless you study. = You won't pass if you don't study.¶unless-ийн дараа үгүйсгэл давхар оруулахгүй: unless you study (unless you don't study биш).|unless + эерэг үйл үг = if ... not|You won't pass unless you study.|Хичээхгүй бол чи тэнцэхгүй.|I'll go unless it rains.|Бороо орохгүй бол би явна.|Don't call me unless it's urgent.|Яаралтай биш бол над руу бүү залга.|Unless we hurry, we'll miss the bus.|Яарахгүй бол бид автобуснаас хоцорно.|You won't pass unless you ___.|study~don't study~will study|I'll go ___ it rains.|unless~if~when|Don't call me unless it ___ urgent.|'s~isn't~won't be
b1|in case|in case — «... болж магадгүй тул, урьдчилан»: Take an umbrella in case it rains. if-ээс ялгаатай нь урьдчилсан бэлтгэлийг заана.¶in case of + нэр үг: In case of fire, use the stairs.|in case + S + Present · in case of + N|Take an umbrella in case it rains.|Бороо орж магадгүй тул шүхэр ав.|I'll write it down in case I forget.|Мартахгүйн тулд бичээд авъя.|Take some money in case you need it.|Хэрэг болж магадгүй тул жаахан мөнгө ав.|In case of fire, use the stairs.|Гал гарвал шатаар гараарай.|Take an umbrella ___ it rains.|in case~if~unless|I'll write it down in case I ___.|forget~will forget~forgot|In case ___ fire, use the stairs.|of~for~in
b1|Relative pronoun орхих: the book I read|Тодотгох өгүүлбэрт who / which / that нь тусагдахуун бол орхиж болно: the book (that) I read. Өгүүлэгдэхүүн бол орхихгүй: the man who lives here.|N + (that) + S + V (тусагдахуун) · N + who / that + V (өгүүлэгдэхүүн — орхихгүй)|This is the book I told you about.|Энэ бол миний чамд ярьсан ном.|The film we saw was great.|Бидний үзсэн кино гайхалтай байсан.|The man who lives next door is a doctor.|Хажуу айлд амьдардаг хүн эмч.|Is this the phone you lost?|Энэ чиний гээсэн утас мөн үү?|The man ___ lives next door is a doctor.|who~-~whom|This is the book ___ I told you about.|-~who~what|The film ___ was great.|we saw~we saw it~saw we
b1|Passive: Present ба Past Simple|Үйлдлийг хэн хийснээс илүү юу болсон нь чухал бол passive: be + V3. Present: English is spoken here. Past: The house was built in 1990.¶Үйлдэгчийг by-оор: The book was written by Tolkien.|am / is / are + V3 · was / were + V3 · by + үйлдэгч|English is spoken all over the world.|Англи хэлээр дэлхий даяар ярьдаг.|This bridge was built in 1990.|Энэ гүүрийг 1990 онд барьсан.|The letters are delivered every morning.|Захидлыг өглөө бүр хүргэдэг.|The book was written by a Mongolian author.|Номыг монгол зохиолч бичсэн.|This bridge ___ in 1990.|was built~built~is built|English ___ all over the world.|is spoken~speaks~spoken|The book was written ___ a Mongolian author.|by~from~with
b1|needn't ба don't need to|needn't / don't need to — «... хийх шаардлагагүй»: You needn't come. You don't need to bring anything.¶mustn't — «хориотой» гэсэн огт өөр утга: You mustn't smoke here.|needn't + V · don't need to + V (шаардлагагүй) · mustn't (хориотой)|You needn't wait for me.|Чи намайг хүлээх шаардлагагүй.|You don't need to bring anything.|Чи юу ч авчрах шаардлагагүй.|You mustn't park here.|Энд машин тавихыг хориглоно.|We didn't need to take a taxi.|Бид такси барих шаардлагагүй байсан.|You ___ wait for me. (шаардлагагүй)|needn't~mustn't~needn't to|You don't need ___ anything.|to bring~bring~bringing|You ___ park here. (хориотой)|mustn't~needn't~don't have to
b1|be able to|can-д ирээдүй, төгс цаг байхгүй тул be able to хэрэглэнэ: I will be able to come. I have never been able to swim.¶Нэг удаагийн амжилтад was able to: I was able to finish on time.|will be able to · have been able to · was able to|I'll be able to help you tomorrow.|Би маргааш чамд тусалж чадна.|I haven't been able to sleep well.|Би сайн унтаж чадахгүй байгаа.|She was able to finish on time.|Тэр цагтаа дуусгаж чадсан.|Will you be able to come?|Чи ирж чадах уу?|I'll ___ help you tomorrow.|be able to~can~able to|I haven't ___ able to sleep well.|been~be~was|She was able ___ on time.|to finish~finish~finishing
b1|manage to|manage to + V — «хэцүү байсан ч амжих, чадах»: I managed to find a taxi. Үгүйсгэл: didn't manage to.|manage to + V · didn't manage to|I managed to find a taxi.|Би такси олж чадсан.|Did you manage to call her?|Чи түүн рүү залгаж амжсан уу?|We didn't manage to finish.|Бид дуусгаж чадаагүй.|She managed to pass the exam.|Тэр шалгалтад тэнцэж чадсан.|I managed ___ a taxi.|to find~finding~find|Did you manage ___ her?|to call~calling~call|We didn't ___ to finish.|manage~managed~managing
b1|be supposed to|be supposed to + V — «... хийх ёстой (дүрэм, хүлээлтээр)»: You're supposed to wear a seatbelt. Өнгөрсөн: was supposed to — ёстой байсан ч болоогүй.|am / is / are supposed to + V · was / were supposed to|You're supposed to wear a seatbelt.|Та хамгаалах бүс зүүх ёстой.|The train was supposed to arrive at 5.|Галт тэрэг таван цагт ирэх ёстой байсан.|What am I supposed to do?|Би юу хийх ёстой юм бэ?|We're not supposed to use phones here.|Энд утас ашиглах ёсгүй.|You're supposed ___ a seatbelt.|to wear~wearing~wear|The train ___ supposed to arrive at 5.|was~is~were
|What ___ I supposed to do?|am~do~is
b1|be about to|be about to + V — «дөнгөж ... гэж байна, одоохон»: The film is about to start. I was about to call you.|am / is / are about to + V · was about to|Hurry up! The film is about to start.|Яар! Кино одоохон эхэлнэ.|I was about to call you.|Би чам руу дөнгөж залгах гэж байсан.|The train is about to leave.|Галт тэрэг хөдлөх гэж байна.|We were about to go out when it rained.|Биднийг гарах гэж байтал бороо орсон.|The film is about ___.|to start~starting~start|I ___ about to call you.|was~am~did|The train is ___ to leave.|about~going~near
b1|want sb to, ask sb to|want / ask / tell / expect / allow + хүн + to + V: I want you to help me. She asked me to wait.¶want that ... хэрэглэхгүй: I want you to come (I want that you come биш).|want / ask / tell / expect / allow + sb + to V|I want you to help me.|Би чамайг надад туслаасай гэж хүсэж байна.|She asked me to wait outside.|Тэр намайг гадаа хүлээхийг хүссэн.|The teacher told us to be quiet.|Багш биднийг чимээгүй бай гэж хэлсэн.|My parents don't allow me to stay out late.|Аав ээж маань намайг орой гадуур байхыг зөвшөөрдөггүй.|I want ___ me.|you to help~that you help~you help
|She asked me ___ outside.|to wait~wait~waiting
|The teacher told ___ quiet.|us to be~us be~to us be
b1|make, let, help + sb + V|make sb do — албадах: She made me clean my room. let sb do — зөвшөөрөх: Let me go. help sb (to) do — туслах. make, let-ийн дараа to-гүй.|make + sb + V · let + sb + V · help + sb + (to) V|My mum made me clean my room.|Ээж маань намайг өрөөгөө цэвэрлүүлсэн.|Let me pay for dinner.|Оройн хоолны мөнгийг би төлье.|He helped me carry the boxes.|Тэр надад хайрцаг зөөхөд тусалсан.|The film made me cry.|Кино намайг уйлуулсан.|My mum made me ___ my room.|clean~to clean~cleaning|Let me ___ for dinner.|pay~to pay~paying|The film made me ___.|cry~to cry~crying
b1|remember, stop, try: -ing уу, to уу|Утга өөрчлөгдөнө: remember to do (хийхээ санах) / remember doing (хийснээ санах). stop to do (... хийхээр зогсох) / stop doing (хийхээ болих). try to do (оролдох) / try doing (туршиж үзэх).|remember / stop / try + to V ба + V-ing — утга өөр|Remember to lock the door.|Хаалгаа түгжихээ мартуузай.|I remember meeting her in 2015.|Би түүнтэй 2015 онд уулзсанаа санаж байна.|He stopped smoking last year.|Тэр өнгөрсөн жил тамхиа хаясан.|We stopped to buy some water.|Бид ус авахаар зогссон.|Remember ___ the door. (мартуузай)|to lock~locking~lock|He stopped ___ last year. (хаясан)|smoking~to smoke~smoke|We stopped ___ some water. (авахаар)|to buy~buying~buy
b1|glad to, surprised to: тэмдэг нэр + to|Мэдрэмжийн тэмдэг нэрийн дараа to + V: I'm glad to see you. She was surprised to hear the news. I'm sorry to hear that.¶Бусад: ready to, afraid to, happy to, pleased to.|glad / happy / sorry / surprised / pleased / ready + to V|I'm glad to see you again.|Чамайг дахин харсандаа баяртай байна.|She was surprised to hear the news.|Тэр мэдээг сонсоод гайхсан.|I'm sorry to hear that.|Үүнийг сонсоод харамсаж байна.|We're ready to start.|Бид эхлэхэд бэлэн.|I'm glad ___ you again.|to see~seeing~see|I'm sorry ___ that.|to hear~hearing~hear|We're ready ___.|to start~starting~start
b1|whereas ба while: эсрэгцүүлэх|Хоёр зүйлийг эсрэгцүүлэхэд whereas, while: My brother is tall, whereas I am short. While some people like tea, others prefer coffee.¶whereas нь бичгийн, while нь ярианд ч түгээмэл.|A, whereas B · While A, B (эсрэгцүүлэх)|My brother is tall, whereas I am short.|Ах маань өндөр, харин би намхан.|While some people like tea, others prefer coffee.|Зарим хүн цайнд дуртай бол зарим нь кофег илүүд үздэг.|The north is cold, whereas the south is warm.|Хойд хэсэг хүйтэн, харин өмнөд хэсэг дулаан.|She loves sports, while her sister prefers books.|Тэр спортод дуртай, харин эгч нь номд дуртай.|My brother is tall, ___ I am short.|whereas~because~so|___ some people like tea, others prefer coffee.|While~During~Unless|The north is cold, ___ the south is warm.|whereas~therefore~so that
b1|in addition, as well as, besides|Нэмэлт мэдээлэл: in addition (to), as well as, besides, moreover, what's more.¶as well as / in addition to + N / V-ing: As well as teaching, she writes books.|in addition (to) · as well as + N / V-ing · besides · what's more|As well as English, she speaks French.|Англиас гадна тэр францаар ярьдаг.|In addition to the salary, you get a car.|Цалингаас гадна машин авна.|Besides, it's too late to go out.|Дээр нь гадагшаа гарахад хэтэрхий оройтсон.|The hotel is cheap. What's more, it's near the beach.|Зочид буудал хямд. Дээр нь далайн эрэгт ойр.|As well ___ English, she speaks French.|as~so~than|In addition ___ the salary, you get a car.|to~of~with|The hotel is cheap. What's ___, it's near the beach.|more~else~also
b1|as a result, that's why: үр дүн|Үр дүн илэрхийлэх: so, as a result, that's why, therefore (албан), consequently (бичгийн).¶as a result of + N: As a result of the storm, the roads were closed.|so · that's why · as a result (of) · therefore|It rained a lot. As a result, the roads were flooded.|Их бороо орсон. Үүний үр дүнд зам үерт автсан.|I missed the bus. That's why I'm late.|Би автобуснаас хоцорсон. Тийм болохоор хоцорлоо.|As a result of the storm, the flights were cancelled.|Шуурганы улмаас нислэгүүд цуцлагдсан.|He studied hard, so he passed.|Тэр сайн хичээсэн тул тэнцсэн.|I missed the bus. ___ I'm late.|That's why~Because~Although|As a result ___ the storm, the flights were cancelled.|of~from~to|He studied hard, ___ he passed.|so~because~although
b1|as, since, due to: шалтгаан|Шалтгаан илэрхийлэх: because, as, since (+ өгүүлбэр), due to, because of (+ нэр үг).¶as / since ихэвчлэн өгүүлбэрийн эхэнд: As it was late, we took a taxi.|as / since + S + V · due to / because of + N|As it was late, we took a taxi.|Орой болсон тул бид такси барьсан.|Since you're here, can you help me?|Чи энд байгаа юм чинь надад туслаач?|The flight was delayed due to bad weather.|Цаг агаар муугаас нислэг хойшилсон.|The match was cancelled due to the rain.|Бороо орсон учир тоглолт цуцлагдсан.|The flight was delayed ___ bad weather.|due to~because~since|___ it was late, we took a taxi.|As~Due to~Because of|Since you're here, ___ you help me?|can~because~so
b1|a ба the: анх ба дахин дурдах|Анх дурдахдаа a / an, дахин дурдахдаа the: I saw a dog. The dog was huge.¶Сонсогч аль нь болохыг мэдэж байвал the: Close the door (энэ өрөөний хаалга).|a / an (анх, аль нэг) · the (дахин дурдсан, мэдэгдэж байгаа)|I bought a shirt and a jacket.|Би цамц, хүрэм авсан.|The shirt was cheap, but the jacket wasn't.|Цамц хямд байсан ч хүрэм нь хямд биш байв.|Can you close the door, please?|Хаалгаа хаачих.|We stayed at a hotel near the sea.|Бид далайн ойролцоох нэг зочид буудалд байрласан.|I saw ___ dog. The dog was huge.|a~the~an
|I saw a dog. ___ dog was huge.|The~A~-
|Can you close ___ door, please?|the~a~-
b1|the rich, the elderly: the + тэмдэг нэр|the + тэмдэг нэр нь бүлэг хүмүүсийг заана, олон тоот үйл үгтэй: the rich (баячууд), the poor, the young, the elderly (өндөр настан), the unemployed.|the + adj = бүлэг хүмүүс (+ олон тоот үйл үг)|The rich should pay more taxes.|Баячууд илүү татвар төлөх ёстой.|We must help the poor.|Бид ядуучуудад туслах ёстой.|The elderly need special care.|Өндөр настанд тусгай халамж хэрэгтэй.|The young are often full of energy.|Залуучууд ихэвчлэн эрч хүчээр дүүрэн байдаг.|The rich ___ pay more taxes.|should~should to~shoulds|We must help ___.|the poor~the poors~poor people the|The elderly ___ special care.|need~needs~is needing
b1|paper ба a paper: утга өөрчлөгдөх|Зарим нэр үг тоолдог, тоолдоггүй хэлбэрээрээ утга өөр: paper (цаас) / a paper (сонин); glass (шил) / a glass (аяга); time (цаг хугацаа) / a time (удаа); room (зай) / a room (өрөө).|paper / a paper · glass / a glass · time / three times · room / a room|I need some paper to write on.|Надад бичих цаас хэрэгтэй.|I bought a paper at the station.|Би буудлаас сонин авсан.|The window is made of glass.|Цонх шилээр хийгдсэн.|Is there room for one more person?|Дахиад нэг хүний зай байна уу?|I bought ___ at the station. (сонин)|a paper~paper~some paper|I need some ___ to write on.|paper~papers~a paper|Is there ___ for one more person? (зай)|room~a room~rooms
b1|police, people, staff: олон тоо|Зарим нэр үг үргэлж олон тоот үйл үгтэй: police, people, cattle. The police are coming.¶staff нь ихэвчлэн олон тоо. person-ийн олон тоо people.|police / people / cattle + are · staff + are|The police are looking for him.|Цагдаа түүнийг эрэн сурвалжилж байна.|People are friendly here.|Энд хүмүүс найрсаг.|Our staff are very helpful.|Манай ажилтнууд их тусч.|Many people were at the concert.|Тоглолтод олон хүн байсан.|The police ___ looking for him.|are~is~has|People ___ friendly here.|are~is~be
|Many ___ were at the concert.|people~peoples~person
b1|family, team + is / are|Бүлэг нэр (family, team, class, government) бүлгийг нэг нэгж гэж үзвэл is, гишүүдийг тус тусад нь бодвол are (ялангуяа британи англид).¶Америк англид ихэвчлэн is.|family / team / class + is (нэгж) / are (гишүүд)|My family is very big.|Манай гэр бүл их том.|The team are training hard for the final.|Баг финалд бэлтгэж шаргуу дасгал хийж байна.|The class is in room 5.|Анги 5-р өрөөнд байна.|The government has made a decision.|Засгийн газар шийдвэр гаргасан.|My family ___ very big. (нэгж)|is~are~be|The government ___ made a decision.|has~have~is
|The class ___ in room 5.|is~are~be
b1|today's news, a week's holiday|Цаг хугацаатай 's: today's news, yesterday's game, a week's holiday, two weeks' time, an hour's walk.¶Олон тоонд зөвхөн apostrophe: in two weeks' time.|today's / yesterday's + N · a week's + N · two weeks' + N|Did you read today's news?|Өнөөдрийн мэдээг уншсан уу?|I need a week's holiday.|Надад нэг долоо хоногийн амралт хэрэгтэй.|The results will be ready in two weeks' time.|Үр дүн хоёр долоо хоногийн дараа гарна.|It's an hour's drive from here.|Эндээс нэг цаг машинаар явах зайтай.|Did you read ___ news?|today's~todays~today|I need a ___ holiday.|week's~weeks~weeks'|in two ___ time|weeks'~week's~weeks
b1|well-known, good-looking: нийлмэл тэмдэг нэр|Хоёр үгийг зураасаар холбож тэмдэг нэр үүсгэнэ: well-known (алдартай), good-looking (царайлаг), short-sleeved, English-speaking, part-time.|well-known · good-looking · part-time · English-speaking · long-haired|She is a well-known writer.|Тэр алдартай зохиолч.|He works part-time in a café.|Тэр кафед хагас цагаар ажилладаг.|They are looking for an English-speaking guide.|Тэд англиар ярьдаг хөтөч хайж байна.|He's a good-looking young man.|Тэр царайлаг залуу.|She is a ___ writer.|well-known~good-known~well-knowing|He works ___ in a café.|part-time~half-time~part-timing|They need an ___ guide.|English-speaking~English-speak~speaking-English
b1|still ба anymore|still — «одоо ч, хэвээрээ»: I still live here. anymore / any longer — «одоо болтол ... -гүй болсон» (үгүйсгэлд, өгүүлбэрийн төгсгөлд): I don't live there anymore.|still (+, одоо ч) · not ... anymore (одоо ... -гүй)|I still remember that day.|Би тэр өдрийг одоо ч санадаг.|She doesn't work here anymore.|Тэр энд ажиллахаа больсон.|Are you still hungry?|Чи өлссөөр л байна уу?|He isn't a child anymore.|Тэр хүүхэд байхаа больсон.|She doesn't work here ___.|anymore~still~yet|Are you ___ hungry?|still~anymore~yet more|I ___ remember that day.|still~anymore~already
b1|even|even — «хүртэл, ч гэсэн»: Even my grandmother uses a smartphone. Харьцуулсан зэргийг хүчтэй болгоно: even better (бүр илүү сайн).¶even if / even though — «... байсан ч гэсэн».|even + N / V · even + comparative · even if / even though|Even my grandmother has a smartphone.|Эмээ хүртэл ухаалаг утастай.|This one is even better.|Энэ нь бүр илүү сайн.|He didn't even say goodbye.|Тэр баяртай ч гэж хэлээгүй.|I'll go even if it rains.|Бороо орсон ч би явна.|___ my grandmother has a smartphone.|Even~Ever~Also|This one is ___ better.|even~very~more
|I'll go even ___ it rains.|if~so~when
b1|hardly, nearly, almost|almost / nearly — «бараг» (дөхсөн ч хүрээгүй): I almost missed the bus. hardly — «бараг ... -гүй» (сөрөг утгатай): I can hardly hear you.¶hardly-тай үгүйсгэл нэмэхгүй: I can hardly see (I can't hardly биш).|almost / nearly (бараг) · hardly (бараг ... -гүй) · hardly ever · hardly any|I almost missed the bus.|Би автобуснаас бараг хоцорчихсон.|It's nearly midnight.|Бараг шөнө дунд боллоо.|I can hardly hear you.|Би чамайг бараг сонсохгүй байна.|There's hardly any milk left.|Сүү бараг үлдсэнгүй.|I can ___ hear you. (бараг ... -гүй)|hardly~almost~nearly|I ___ missed the bus. (бараг)|almost~hardly~most|There's hardly ___ milk left.|any~no~some
b1|much / far + харьцуулсан зэрэг|Харьцуулсан зэргийг хүчтэй болгох: much, far, a lot + -er / more: much bigger, far more expensive. Бага зэрэг: a bit, slightly: a bit cheaper.¶very-г харьцуулсан зэрэгтэй хэрэглэхгүй: very bigger биш.|much / far / a lot + comparative · a bit / slightly + comparative|This car is much faster than mine.|Энэ машин минийхээс хамаагүй хурдан.|Living here is far more expensive.|Энд амьдрах бүр ч үнэтэй.|The new flat is a bit bigger.|Шинэ байр арай том.|Today is slightly warmer than yesterday.|Өнөөдөр өчигдрөөс арай дулаан.|This car is ___ faster than mine.|much~very~many|The new flat is ___ bigger.|a bit~a few~bit
|Living here is ___ more expensive.|far~very~many
b1|the best I've ever seen|Хамгийн + Present Perfect + ever: It's the best film I've ever seen. This is the most beautiful place I've ever visited.|the + superlative + N + (that) + S + have ever + V3|It's the best film I've ever seen.|Энэ бол миний үзсэн хамгийн сайн кино.|She's the kindest person I've ever met.|Тэр бол миний уулзсан хамгийн сайхан сэтгэлтэй хүн.|This is the most beautiful place I've ever visited.|Энэ бол миний очсон хамгийн гоё газар.|That was the worst meal I've ever had.|Тэр бол миний идсэн хамгийн муу хоол.|It's the best film I've ___ seen.|ever~never~already|She's the ___ person I've ever met.|kindest~kinder~most kind
|That was the worst meal I've ever ___.|had~have~having
b1|Did you? Really?: хариу асуулт|Ярианд сонирхол, гайхлаа илэрхийлэхдээ туслах үйл үгээр богино асуулт: I went to Paris. — Did you? She's getting married. — Is she? Really?|туслах үйл үг + өгүүлэгдэхүүн?: Did you? Is she? Have you? Can he?|I've been to Japan. — Have you? When?|Би Японд очсон. — Тийм үү? Хэзээ?|She's getting married. — Is she? Really?|Тэр гэрлэх гэж байна. — Тийм үү? Үнэхээр үү?|I can speak four languages. — Can you?|Би дөрвөн хэлээр ярьдаг. — Тийм үү?|He lost his job. — Did he? That's terrible.|Тэр ажилгүй болсон. — Тийм үү? Ямар харамсалтай.|I've been to Japan. — ___ you?|Have~Did~Are|She's getting married. — ___ she?|Is~Does~Has|He lost his job. — ___ he?|Did~Has~Was
b1|Phrasal verbs: аялал|Аялалтай холбоотой phrasal verb: set off (гарах, хөдлөх), check in / check out (бүртгүүлэх / гарах), take off (онгоц хөөрөх), get away (амрахаар явах), pick up (тосож авах).|set off · check in / out · take off · pick up · see off · get away|We set off early in the morning.|Бид өглөө эрт гарсан.|We checked in at the hotel at two.|Бид хоёр цагт зочид буудалд бүртгүүлсэн.|The plane took off on time.|Онгоц цагтаа хөөрсөн.|Can you pick me up from the airport?|Намайг нисэх буудлаас тосож авч чадах уу?|The plane took ___ on time.|off~up~out|We ___ off early in the morning.|set~got~put|Can you pick me ___ from the airport?|up~off~out
b1|Phrasal verbs: ажил|Ажлын орчинд: carry on (үргэлжлүүлэх), set up (байгуулах), take on (ажилд авах, хүлээж авах), fill in (бөглөх), hand in (хүлээлгэн өгөх), look into (судлах).|carry on · set up · take on · fill in · hand in · look into|Please fill in this form.|Энэ маягтыг бөглөнө үү.|She set up her own company.|Тэр өөрийн компани байгуулсан.|We'll look into the problem.|Бид асуудлыг судалж үзнэ.|Hand in your reports by Friday.|Тайлангаа баасан гараг гэхэд өгөөрэй.|Please fill ___ this form.|in~up~out of|She set ___ her own company.|up~on~in|We'll look ___ the problem.|into~at~after
b1|Phrasal verbs: харилцаа|Хүмүүсийн харилцаа: get on (well) with (эвтэй байх), fall out with (муудалцах), make up (эвлэрэх), look up to (хүндлэх), let down (урам хугалах), break up (салах).|get on with · fall out with · make up · look up to · let down · break up|I get on well with my sister.|Би эгчтэйгээ эвтэй.|They fell out over money.|Тэд мөнгөнөөс болж муудалцсан.|They had a fight but made up quickly.|Тэд муудалцсан ч хурдан эвлэрсэн.|I look up to my grandfather.|Би өвөөгөө хүндэлдэг.|I get ___ well with my sister.|on~in~up|They had a fight but made ___ quickly.|up~out~off|I look ___ to my grandfather.|up~after~out
b1|Phrasal verbs: өдөр тутам|Өдөр тутамд: run out of (дуусах), give up (орхих), find out (олж мэдэх), put off (хойшлуулах), throw away (хаях), look after (асрах).|run out of · give up · find out · put off · throw away · look after|We've run out of milk.|Сүү дуусчихсан.|Don't give up. You can do it!|Бүү бууж өг. Чи чадна!|I found out the truth yesterday.|Би үнэнийг өчигдөр олж мэдсэн.|She looks after her little brother.|Тэр дүүгээ асардаг.|We've run ___ of milk.|out~off~away|Don't give ___.|up~in~out|She looks ___ her little brother.|after~for~at
b1|Phrasal verbs: мэдрэмж|Сэтгэл хөдлөл: cheer up (баярлуулах), calm down (тайвшрах), freak out (сандрах), get over (даван туулах), put up with (тэвчих), cool down.|cheer up · calm down · get over · put up with · freak out|Cheer up! It's not so bad.|Сэтгэлээ сэргээ! Тийм ч муу биш.|Calm down and tell me what happened.|Тайвшраад юу болсныг хэл.|It took her a year to get over it.|Үүнийг даван туулахад түүнд нэг жил зарцуулсан.|I can't put up with this noise.|Би энэ чимээг тэвчиж чадахгүй.|___ down and tell me what happened.|Calm~Cheer~Cool up|It took her a year to get ___ it.|over~off~through up|I can't put up ___ this noise.|with~for~at
b1|take a photo, take a break|take-тэй тогтмол хослол: take a photo, take a break, take a seat, take a risk, take care, take part (in), take place (болох).|take a photo / a break / a seat / a risk / care · take part in · take place|Let's take a break.|Завсарлага авъя.|Can you take a photo of us?|Бидний зургийг авч өгөхгүй юу?|The concert will take place in the park.|Тоглолт цэцэрлэгт хүрээлэнд болно.|She took part in the competition.|Тэр тэмцээнд оролцсон.|Let's ___ a break.|take~make~do|The concert will take ___ in the park.|place~part~time|She took ___ in the competition.|part~place~care
b1|-tion, -ment, -ness: нэр үг бүтээх|Үйл үгээс нэр үг: -tion / -sion (decide → decision, inform → information), -ment (develop → development). Тэмдэг нэрээс: -ness (happy → happiness), -ity (possible → possibility).|V + tion / ment · adj + ness / ity|We need to make a decision.|Бид шийдвэр гаргах хэрэгтэй.|The development of the city is fast.|Хотын хөгжил хурдан байна.|Money doesn't buy happiness.|Мөнгөөр аз жаргал худалдаж авахгүй.|Thank you for the information.|Мэдээлэлд баярлалаа.|We need to make a ___. (decide)|decision~decidement~decideness|Money doesn't buy ___. (happy)|happiness~happyness~happiment|The ___ of the city is fast. (develop)|development~develoption~developness
b1|-ful, -less, -able: тэмдэг нэр бүтээх|-ful — «... -тай, дүүрэн»: useful, careful. -less — «... -гүй»: useless, careless. -able / -ible — «... болохуйц»: comfortable, possible.¶Жишээ: help → helpful / helpless.|N + ful / less · V + able|This app is very useful.|Энэ апп их хэрэгтэй.|Be careful! The floor is wet.|Болгоомжтой! Шал нойтон байна.|That was a careless mistake.|Энэ хайхрамжгүй алдаа байлаа.|This chair is very comfortable.|Энэ сандал их тухтай.|Be ___! The floor is wet.|careful~careless~caring|This app is very ___.|useful~useless~usable ful|That was a ___ mistake. (хайхрамжгүй)|careless~careful~uncareful
b1|rise ба raise|rise (rose, risen) — өөрөө өсөх, мандах (тусагдахуунгүй): Prices rose. The sun rises. raise (raised) — ямар нэг зүйлийг өргөх, өсгөх (тусагдахуунтай): Raise your hand. They raised prices.|rise — rose — risen (өөрөө) · raise — raised (ямар нэгийг)|The sun rises in the east.|Нар зүүнээс мандана.|Prices rose by 10% last year.|Өнгөрсөн жил үнэ 10%-иар өссөн.|Raise your hand if you know the answer.|Хариултыг мэдэж байвал гараа өргө.|They raised money for the school.|Тэд сургуульд зориулж мөнгө цуглуулсан.|The sun ___ in the east.|rises~raises~rise
|___ your hand if you know the answer.|Raise~Rise~Rose
|Prices ___ by 10% last year.|rose~raised~rised
b1|fun ба funny|fun — «хөгжилтэй, таатай (цаг өнгөрөөх)»: The party was fun. funny — «инээдтэй»: a funny joke.¶have fun — сайхан цагийг өнгөрөөх.|fun (таатай) · funny (инээдтэй) · have fun|The party was really fun.|Үдэшлэг их хөгжилтэй байсан.|He told a funny joke.|Тэр инээдтэй хошигнол ярьсан.|Have fun at the beach!|Далайн эрэгт сайхан амраарай!|Learning languages is fun.|Хэл сурах сонирхолтой.|He told a ___ joke. (инээдтэй)|funny~fun~funnily|Have ___ at the beach!|fun~funny~a fun|The party was really ___.|fun~funny~funs
b1|remind ба remember|remember — өөрөө санах: I remember her name. remind — бусдад сануулах: Remind me to call Mum. remind sb of sth — ... -ийг санагдуулах: You remind me of my sister.|remember + sth · remind + sb + to V · remind + sb + of + sth|Remind me to buy bread.|Талх авахыг надад сануулаарай.|I don't remember his name.|Би түүний нэрийг санахгүй байна.|You remind me of my sister.|Чи надад эгчийг минь санагдуулдаг.|This song reminds me of summer.|Энэ дуу надад зуныг санагдуулдаг.|___ me to buy bread.|Remind~Remember~Recall
|You remind me ___ my sister.|of~to~about me
|I don't ___ his name.|remember~remind~remind me
b1|win, earn, gain|win — тэмцээн, шагнал хожих: win a match, win a prize. earn — ажлаар мөнгө олох: earn money. gain — аажмаар олж авах: gain experience, gain weight.|win + match / prize · earn + money · gain + experience / weight|Our team won the match.|Манай баг тоглолтод хожсон.|She earns a good salary.|Тэр сайн цалин авдаг.|I gained a lot of experience.|Би их туршлага хуримтлуулсан.|He won first prize.|Тэр тэргүүн байрын шагнал хүртсэн.|She ___ a good salary.|earns~wins~gains money|Our team ___ the match.|won~earned~gained|I ___ a lot of experience.|gained~won~earned money
b1|job ба work|work — тоолдоггүй, ерөнхий ажил: I have a lot of work. I go to work. job — тоолдог, тодорхой ажлын байр: I have a new job.¶work нь үйл үг ч болно: I work in a bank.|work (тоолдоггүй) · a job (тоолдог) · go to work|I have a lot of work today.|Надад өнөөдөр их ажил байна.|She got a new job.|Тэр шинэ ажилд орсон.|What time do you finish work?|Чи хэдэн цагт ажлаа тардаг вэ?|He's looking for a job.|Тэр ажил хайж байна.|She got a new ___.|job~work~works|I have a lot of ___ today.|work~jobs~job
|He's looking for ___.|a job~a work~work job
b1|actually ба currently|actually — «үнэндээ, чухамдаа» (бодит байдлыг онцлох): Actually, I'm from Darkhan. currently — «одоогоор, одоо»: She is currently working in Seoul.¶Монгол «актуаль» гэсэнтэй андуурахгүй.|actually (үнэндээ) · currently (одоогоор)|Actually, I've never been there.|Үнэндээ би тэнд хэзээ ч очиж байгаагүй.|She is currently living in Seoul.|Тэр одоогоор Сөүлд амьдарч байна.|It looks easy, but actually it's very hard.|Амархан харагдах ч үнэндээ их хэцүү.|We are currently looking for new staff.|Бид одоогоор шинэ ажилтан хайж байна.|She is ___ living in Seoul. (одоогоор)|currently~actually~actual|It looks easy, but ___ it's very hard.|actually~currently~now
|We are ___ looking for new staff.|currently~actually~actual
b1|tend to|tend to + V — «... хандлагатай, ихэвчлэн ...»: I tend to eat too much. Үгүйсгэл: don't tend to.|tend to + V · there tends to be|I tend to go to bed late.|Би ихэвчлэн оройтож унтдаг.|People tend to spend more at weekends.|Хүмүүс амралтын өдөр илүү мөнгө зарцуулах хандлагатай.|She tends to worry too much.|Тэр хэт их санаа зовох хандлагатай.|It tends to rain in April.|Дөрөвдүгээр сард бороо их ордог.|I tend ___ to bed late.|to go~going~go|She ___ to worry too much.|tends~tend~tending
|People tend to ___ more at weekends.|spend~spending~spent
`]);
