(window.LP=window.LP||[]).push(["es",1,`
a1|Хүйс ба тодотгол үг: el, la, un, una|Испани хэлэнд нэр үг эр (masculino) эсвэл эм (femenino) хүйстэй. Ихэвчлэн -o-оор төгссөн нь эр, -a-аар төгссөн нь эм.¶Тодорхой: el, la, los, las. Тодорхой бус: un, una, unos, unas. Онцгой: el día, la mano, el problema.|el libro · la casa · los niños · las flores · un perro · una manzana|El gato es negro.|Муур хар.|Tengo una hermana.|Би нэг эгчтэй.|Los niños juegan.|Хүүхдүүд тоглож байна.|Es un libro interesante.|Энэ сонирхолтой ном.|___ casa es grande.|La~El~Los|Tengo ___ perro. (нэг)|un~una~unos|___ flores son bonitas.|Las~Los~La
a1|ser ба estar: хоёр «байх»|ser — байнгын шинж, хэн, юу болох, хаанаас: Soy mongol. estar — түр зуурын байдал, мэдрэмж, байрлал: Estoy cansado. Estoy en casa.¶ser: soy, eres, es, somos, sois, son. estar: estoy, estás, está, estamos, estáis, están.|ser: soy, eres, es · estar: estoy, estás, está|Soy de Mongolia.|Би Монголоос ирсэн.|Estoy muy cansado.|Би их ядарч байна.|Madrid está en España.|Мадрид Испанид байдаг.|Ella es profesora.|Тэр багш.|Yo ___ estudiante.|soy~estoy~es|Hoy ___ muy contento. (би)|estoy~soy~está|¿Dónde ___ el baño?|está~es~son
a1|-ar үйл үг: одоо цаг|-ar-аар төгссөн үйл үгс (hablar, trabajar, estudiar) хамгийн түгээмэл. -ar-ийг авч төгсгөл залгана.¶yo -o, tú -as, él/ella -a, nosotros -amos, vosotros -áis, ellos -an. Төлөөний үгийг ихэвчлэн орхидог: Hablo español.|hablo · hablas · habla · hablamos · habláis · hablan|Hablo un poco de español.|Би бага зэрэг испаниар ярьдаг.|¿Trabajas aquí?|Чи энд ажилладаг уу?|Nosotros estudiamos juntos.|Бид хамт хичээллэдэг.|Ellos viajan mucho.|Тэд их аялдаг.|Yo ___ en un banco. (trabajar)|trabajo~trabajas~trabaja|¿Tú ___ inglés? (hablar)|hablas~hablo~hablan|Nosotros ___ música. (escuchar)|escuchamos~escucháis~escuchan
a1|tener ба hay|tener — -тай байх, эзэмших: Tengo un gato. Нас хэлэхэд: Tengo veinte años. Мэдрэмж: tengo hambre (өлсөж байна), tengo frío (даарч байна).¶hay — бий, байна (англи there is/are): Hay un banco aquí. tener: tengo, tienes, tiene, tenemos, tenéis, tienen.|tengo · tienes · tiene · hay (бий) · no hay (алга)|Tengo veinte años.|Би хорин настай.|¿Tienes hermanos?|Чи ах дүүтэй юу?|Hay un supermercado cerca.|Ойрхон супермаркет бий.|No hay leche en casa.|Гэрт сүү алга.|Yo ___ hambre.|tengo~tiene~hay|¿___ un hotel por aquí?|Hay~Tiene~Es|Ella ___ dos hijos.|tiene~tengo~hay
a1|gustar: дуртай байх|gustar нь «таалагдах» гэсэн утгатай: Me gusta el café — Надад кофе таалагддаг. Дуртай зүйл олон тоотой бол gustan.¶me gusta (надад), te gusta (чамд), le gusta (түүнд), nos gusta (бидэнд), les gusta (тэдэнд).|me gusta + нэг зүйл · me gustan + олон зүйл · me gusta + үйл үг|Me gusta el café.|Би кофенд дуртай.|¿Te gustan los gatos?|Чи мууранд дуртай юу?|Nos gusta viajar.|Бид аялах дуртай.|A mi madre le gustan las flores.|Ээж маань цэцэгт дуртай.|Me ___ las manzanas.|gustan~gusta~gusto|¿Te ___ bailar?|gusta~gustan~gustas|A él ___ gusta el fútbol.|le~me~te
a2|Ойрын ирээдүй: ir a + үйл үг|Удахгүй болох үйлийг ir (явах) + a + үйл үгийн үндсэн хэлбэрээр хэлнэ.¶ir: voy, vas, va, vamos, vais, van.|voy a comer · vas a ver · vamos a viajar|Voy a aprender español.|Би испани хэл сурна.|Va a llover.|Бороо орох гэж байна.|Vamos a viajar en verano.|Бид зун аялна.|¿Qué vas a hacer mañana?|Маргааш чи юу хийх вэ?|Yo ___ a estudiar.|voy~vas~va|Nosotros ___ a comer fuera.|vamos~van~vais|Ellos ___ a llegar tarde.|van~va~vamos
a2|Pretérito perfecto: he comido|Өнөөдөр, энэ долоо хоногт гэх мэт одоотой холбоотой өнгөрсөн үйл: haber + дагавар хэлбэр. -ar → -ado, -er/-ir → -ido.¶haber: he, has, ha, hemos, habéis, han. Онцгой: hacer → hecho, ver → visto, escribir → escrito.|he hablado · has comido · ha vivido · hemos visto|Hoy he trabajado mucho.|Өнөөдөр би их ажилласан.|¿Has comido ya?|Чи хоол идчихсэн үү?|Nunca he estado en España.|Би Испанид хэзээ ч очиж байгаагүй.|Hemos visto una película.|Бид кино үзсэн.|Yo ___ terminado el trabajo.|he~ha~has|¿Tú ___ visto a Ana?|has~he~ha|Ellos han ___ (comer)|comido~comado~comen
a1|Тэмдэг нэрийн зохицол|Тэмдэг нэр нэр үгийнхээ хүйс, тоотой зохицож, ихэвчлэн ард нь ордог: una casa blanca.¶-o → -a (эм): rojo → roja. Олон тоо: -s эсвэл -es: rojos, azules. -e-ээр төгссөн нь хүйсээр өөрчлөгдөхгүй: grande.|rojo, roja, rojos, rojas · grande, grandes · azul, azules|Tengo una casa pequeña.|Би жижиг байшинтай.|Ella lleva un vestido azul.|Тэр цэнхэр даашинз өмссөн.|Mis amigos son simpáticos.|Найзууд маань найрсаг.|Las flores son bonitas.|Цэцэгнүүд гоё.|Una camisa ___ (blanco)|blanca~blanco~blancos|Los coches ___ (rojo)|rojos~rojas~roja|Las casas son ___ (grande)|grandes~granda~grande
`]);
