(window.LP=window.LP||[]).push(["en",5,`
b1|Зөвлөгөө өгөх хэлбэрүүд|Зөвлөгөө өгөх олон арга: You should ..., You ought to ..., You'd better ... (хүчтэй, анхааруулга), Why don't you ...?, If I were you, I'd ..., It might be a good idea to ...|should · ought to · had better · Why don't you ...? · It might be a good idea to ...|You should get more sleep.|Чи илүү их унтах хэрэгтэй.|You'd better hurry or you'll miss the train.|Яарсан нь дээр, эс тэгвэл галт тэрэгнээс хоцорно.|Why don't you ask your teacher?|Багшаасаа асуувал яасан юм бэ?|It might be a good idea to book early.|Эрт захиалсан нь зүгээр байх.|You'd better ___ or you'll miss the train.|hurry~to hurry~hurrying|You ought ___ more sleep.|to get~get~getting|Why don't you ___ your teacher?|ask~to ask~asking
b1|I see your point, but ...: эелдгээр санал зөрөх|Эелдгээр санал зөрөх: I see your point, but ... / I understand what you mean, but ... / That's true, but ... / I'm not so sure.¶Шууд I don't agree гэхээс илүү зөөлөн.|I see your point, but ... · That's true, but ... · I'm not so sure · I see what you mean|I see your point, but it's too expensive.|Санааг чинь ойлгож байна, гэхдээ хэтэрхий үнэтэй.|That's true, but we don't have time.|Үнэн, гэхдээ бидэнд цаг алга.|I see what you mean, but I disagree.|Юу хэлээд байгааг чинь ойлгож байна, гэхдээ би санал нийлэхгүй.|I'm not so sure about that.|Би үүнд тийм ч итгэлтэй биш байна.|I see your ___, but it's too expensive.|point~idea of~meaning|I see what you ___, but I disagree.|mean~say it~think it|I'm not so ___ about that.|sure~agree~right
b1|What I mean is ...: тодруулах|Хэлсэн зүйлээ тодруулах: What I mean is ... / In other words, ... / Let me put it another way. Бусдаас тодруулах: Do you mean ...? What do you mean by ...?|What I mean is ... · In other words ... · Do you mean ...? · What do you mean by ...?|What I mean is, we need more time.|Миний хэлэх гэсэн нь бидэнд илүү цаг хэрэгтэй.|In other words, the plan failed.|Өөрөөр хэлбэл төлөвлөгөө бүтэлгүйтсэн.|Do you mean we should start again?|Бид дахин эхлэх ёстой гэсэн үү?|What do you mean by "soon"?|«Удахгүй» гэж юуг хэлж байна вэ?|What I ___ is, we need more time.|mean~say~think|In other ___, the plan failed.|words~ways~terms|What do you mean ___ "soon"?|by~with~of
b1|I'm calling about ...: албан утасны яриа|Албан утасны яриа: I'm calling about ... / I'm phoning to ask ... / Could you put me through to ...? / Could I leave a message? / I'll call back later.|I'm calling about ... · Could you put me through to ...? · Could I leave a message? · I'll call back|I'm calling about the job advertisement.|Би ажлын зарын талаар залгаж байна.|Could you put me through to the manager?|Менежертэй холбож өгөхгүй юу?|Could I leave a message for her?|Түүнд дамжуулах зүйл үлдээж болох уу?|I'll call back later.|Би дараа дахин залгана.|I'm calling ___ the job advertisement.|about~for~on|Could you put me ___ to the manager?|through~on~up|I'll call ___ later.|back~again~return
b1|I am writing to ...: албан имэйл|Албан захидлын эхлэл: I am writing to enquire about ... / to apply for ... / to complain about ... Төгсгөл: I look forward to hearing from you. Yours sincerely / faithfully.¶Албан бичигт товчлол (I'm, don't) хэрэглэхгүй.|I am writing to + V · I would be grateful if ... · I look forward to hearing from you|I am writing to apply for the position of assistant.|Би туслахын ажлын байранд өргөдөл гаргахаар бичиж байна.|I am writing to complain about the service.|Үйлчилгээний талаар гомдол гаргахаар бичиж байна.|I would be grateful if you could reply soon.|Та удахгүй хариулбал талархах болно.|I look forward to hearing from you.|Таны хариуг хүлээж байна.|I am writing ___ for the position.|to apply~for apply~applying|I would be grateful ___ you could reply soon.|if~that~when|I look forward to ___ from you.|hearing~hear~be heard
b1|Түүх ярих цагууд|Түүх ярихдаа: дэвсгэр — Past Continuous (It was raining ...), гол үйл явдал — Past Simple (Suddenly, a man appeared), өмнө болсон зүйл — Past Perfect (I had forgotten my key).|Past Continuous (дэвсгэр) · Past Simple (үйл явдал) · Past Perfect (өмнө нь)|It was raining and the wind was blowing.|Бороо орж, салхи салхилж байв.|Suddenly, someone knocked on the door.|Гэнэт хэн нэгэн хаалга тогшив.|I couldn't get in because I had lost my key.|Би түлхүүрээ гээчихсэн байсан тул орж чадсангүй.|When we arrived, the film had already started.|Биднийг очиход кино аль хэдийн эхэлчихсэн байв.|It ___ and the wind was blowing. (дэвсгэр)|was raining~rained~had rained|Suddenly, someone ___ on the door.|knocked~was knocking~had knocked|When we arrived, the film ___ already started.|had~has~was
b1|each other ба themselves|each other — «бие биенээ» (харилцан): They love each other. themselves — «өөрсдийгөө» (тус бүр өөртөө): They hurt themselves.|each other (харилцан) · themselves / ourselves (өөрсдийгөө)|Tom and Anna love each other.|Том, Анна хоёр бие биедээ хайртай.|We help each other with homework.|Бид гэрийн даалгавар дээр бие биедээ тусалдаг.|The children enjoyed themselves at the party.|Хүүхдүүд үдэшлэгт сайхан цагийг өнгөрүүлсэн.|They looked at themselves in the mirror.|Тэд толинд өөрсдийгөө харсан.|Tom and Anna love ___.|each other~themselves~theirselves|The children enjoyed ___ at the party.|themselves~each other~them|We help ___ with homework.|each other~ourselves each~us
b1|plenty of, several, a great deal of|Тоо хэмжээ: plenty of — «хангалттай их» (тоолдог, тоолдоггүй), several — «хэд хэдэн» (тоолдог), a great deal of — «маш их» (тоолдоггүй, албан).|plenty of + N · several + олон тоо · a great deal of + тоолдоггүй N|Don't worry, we have plenty of time.|Санаа зоволтгүй, бидэнд цаг хангалттай бий.|I've been there several times.|Би тэнд хэд хэдэн удаа очсон.|She spent a great deal of money on it.|Тэр үүнд маш их мөнгө зарцуулсан.|There are plenty of shops near here.|Энд ойрхон олон дэлгүүр бий.|We have ___ of time.|plenty~many~several|I've been there ___ times.|several~a great deal~plenty
|She spent a great ___ of money on it.|deal~lot~many
b1|whole ба all|the whole + ганц тоот нэр — «бүхэл, бүтэн»: the whole day, the whole class. all + олон тоо эсвэл all (of) the + N: all the students, all day.|the whole + N (ганц) · all (the) + N|I spent the whole day at home.|Би бүтэн өдрийг гэртээ өнгөрөөсөн.|The whole class passed the exam.|Анги бүхэлдээ шалгалтад тэнцсэн.|All the students passed.|Бүх сурагч тэнцсэн.|She ate the whole cake!|Тэр бялууг бүтнээр нь идчихсэн!|I spent the ___ day at home.|whole~all~total|___ the students passed.|All~Whole~The whole
|She ate the ___ cake!|whole~all~every
b1|about, around, over, nearly: ойролцоо тоо|Ойролцоо тоо: about / around / approximately (орчим), over / more than (-аас дээш), nearly / almost (бараг), under / less than (-аас доош).|about / around · over / more than · nearly / almost · under / less than|About fifty people came.|Тавь орчим хүн ирсэн.|The trip costs over two thousand dollars.|Аялал хоёр мянган доллараас илүү.|It's nearly ten o'clock.|Бараг арван цаг болж байна.|Children under twelve travel free.|Арван хоёроос доош насны хүүхэд үнэгүй зорчино.|___ fifty people came. (орчим)|About~Over~Nearly to|Children ___ twelve travel free.|under~below of~less|The trip costs ___ two thousand dollars. (-аас илүү)|over~about~nearly
b1|was going to: биелээгүй төлөвлөгөө|was / were going to — «... хийх гэж байсан (гэвч болоогүй)»: I was going to call you, but I forgot.|was / were going to + V (биелээгүй төлөвлөгөө)|I was going to call you, but I forgot.|Би чам руу залгах гэж байсан ч мартчихсан.|We were going to go out, but it rained.|Бид гадагшаа гарах гэж байсан ч бороо орсон.|She was going to study medicine.|Тэр анагаах ухаан сурах гэж байсан.|What were you going to say?|Чи юу хэлэх гэж байсан бэ?|I ___ going to call you, but I forgot.|was~am~did|We were going ___ out, but it rained.|to go~go~going
|What ___ you going to say?|were~did~are
b1|What ... for?|What ... for? — «юунд, ямар зорилгоор?»: What is this button for? What did you do that for?¶Хариулт: It's for + V-ing / N, эсвэл To + V.|What + ... + for? — It's for + V-ing / To + V|What is this button for?|Энэ товч юунд зориулагдсан бэ?|It's for turning off the machine.|Машиныг унтраахад зориулсан.|What did you say that for?|Чи яагаад тэгж хэлсэн юм бэ?|What do you need the money for? — To buy a ticket.|Мөнгө юунд хэрэгтэй вэ? — Билет авахад.|What is this button ___?|for~to~about|It's for ___ off the machine.|turning~turn~to turn|What do you need the money for? — ___ buy a ticket.|To~For~For to
b1|It's worth + -ing|It's worth + V-ing — «... хийх нь үнэ цэнэтэй, зүйтэй»: The museum is worth visiting. It's not worth waiting.¶worth + мөнгө: It's worth $100.|be worth + V-ing · It's (not) worth + V-ing · worth + мөнгө|The museum is worth visiting.|Музейд очиж үзэх нь зүйтэй.|It's not worth waiting. Let's go.|Хүлээх нь утгагүй. Явъя.|Is this book worth reading?|Энэ номыг унших нь зүйтэй юу?|This painting is worth a lot of money.|Энэ зураг маш их үнэтэй.|The museum is worth ___.|visiting~to visit~visit|It's not worth ___. Let's go.|waiting~to wait~wait|Is this book worth ___?|reading~to read~read
b1|There's no point in + -ing|There's no point (in) + V-ing — «... -ад утга алга»: There's no point in arguing. What's the point of + V-ing?|There's no point (in) + V-ing · What's the point of + V-ing?|There's no point in arguing.|Маргах утгагүй.|There's no point waiting for him.|Түүнийг хүлээхэд утга алга.|What's the point of buying it?|Үүнийг авах ямар учиртай юм бэ?|There's no point in worrying.|Санаа зовоод нэмэргүй.|There's no point in ___.|arguing~to argue~argue|What's the point ___ buying it?|of~in to~for to|There's no point ___ for him.|waiting~to wait~wait
b1|can't help + -ing|can't help + V-ing — «... -ахаас өөрийгөө барьж чадахгүй»: I can't help laughing. She couldn't help crying.|can't / couldn't help + V-ing|I can't help laughing when I see him.|Түүнийг харахаар инээдээ барьж чаддаггүй.|She couldn't help crying at the end.|Тэр төгсгөлд нь уйлахаас өөрийгөө барьж чадаагүй.|I can't help thinking about it.|Би энэ тухай бодохоос өөрийгөө барьж чадахгүй байна.|He can't help eating sweets.|Тэр чихэр идэхээс өөрийгөө барьж чаддаггүй.|I can't help ___ when I see him.|laughing~to laugh~laugh|She couldn't help ___ at the end.|crying~to cry~cry
|I can't help ___ about it.|thinking~to think~think
b1|look forward to + -ing|look forward to — «... -ыг тэсэн ядан хүлээх». Энд to нь угтвар тул V-ing: I'm looking forward to seeing you (to see биш).|look forward to + N / V-ing|I'm looking forward to seeing you.|Чамтай уулзахыг тэсэн ядан хүлээж байна.|We're looking forward to the holidays.|Бид амралтаа тэсэн ядан хүлээж байна.|She is looking forward to starting her new job.|Тэр шинэ ажлаа эхлэхийг тэсэн ядан хүлээж байна.|I look forward to hearing from you.|Таны хариуг хүлээж байна.|I'm looking forward to ___ you.|seeing~see~to see|She is looking forward ___ her new job.|to starting~to start~starting
|We're looking forward to ___ holidays.|the~see the~seeing the the
b1|any: аль нь ч хамаагүй|Эерэг өгүүлбэрт any — «аль нь ч хамаагүй»: Take any seat. You can call me any time. Anyone can do it.|any + N (аль нь ч хамаагүй) · anyone · anything · any time|Take any seat you like.|Хүссэн суудалдаа суу.|You can call me any time.|Хэзээ ч хамаагүй над руу залгаж болно.|Anyone can learn to swim.|Хэн ч сэлж сурч чадна.|Any bus will take you to the centre.|Аль ч автобус чамайг төв рүү хүргэнэ.|Take ___ seat you like.|any~some~every|___ can learn to swim.|Anyone~Someone~No one
|You can call me ___ time.|any~some~every
b1|else: something else, who else|else — «өөр, бас»: something else, someone else, anything else, what else, who else, where else.¶else нь үгийн ард орно: who else (else who биш).|something / someone / anything else · what / who / where else|Would you like anything else?|Өөр юм авах уу?|Who else is coming?|Өөр хэн ирэх вэ?|Let's go somewhere else.|Өөр газар явъя.|That's not mine. It's someone else's.|Энэ минийх биш. Өөр хүнийх.|Would you like anything ___?|else~more other~other|Who ___ is coming?|else~other~more
|Let's go ___.|somewhere else~else somewhere~somewhere other
b1|whatever, wherever, whoever|-ever — «ямар ч, хаана ч, хэн ч» гэсэн утга: Do whatever you want. Sit wherever you like. Whoever wins, we'll celebrate.|whatever · wherever · whoever · whenever · however + adj|Do whatever you want.|Хүссэн бүхнээ хий.|Sit wherever you like.|Хаана ч хамаагүй суу.|Call me whenever you need help.|Тусламж хэрэгтэй үедээ хэзээ ч над руу залга.|Whoever finishes first wins.|Хэн эхэлж дуусгана тэр нь хожно.|Do ___ you want.|whatever~what~whichever of|Sit ___ you like.|wherever~where~whatever
|Call me ___ you need help.|whenever~when ever~whatever
b1|own: my own, on my own|my / your + own — «өөрийн (бусдынх биш)»: I have my own room. on my own — «ганцаараа, өөрөө»: I live on my own. = by myself.|my / your / his + own + N · on my own = by myself|I want my own room.|Би өөрийн гэсэн өрөөтэй болмоор байна.|She lives on her own.|Тэр ганцаараа амьдардаг.|He built the house on his own.|Тэр байшинг ганцаараа барьсан.|Is this your own car?|Энэ өөрийн чинь машин уу?|I want my ___ room.|own~self~alone|She lives on her ___.|own~self~alone
|He built the house ___ his own.|on~by~of
b1|such as ба like: жишээ|Жишээ дурдахад such as (албан) эсвэл like (ярианд): I like sports such as tennis and golf. = like tennis and golf.¶for example / for instance — өгүүлбэрийн эхэнд.|such as + N · like + N (ярианд) · for example, ...|I enjoy sports such as tennis and swimming.|Би теннис, сэлэлт зэрэг спортод дуртай.|We visited cities like Paris and Rome.|Бид Парис, Ром зэрэг хотуудаар аялсан.|Some fruits, for example oranges, have a lot of vitamin C.|Зарим жимс, жишээ нь жүрж, их С аминдэмтэй.|Eat healthy food such as vegetables.|Хүнсний ногоо гэх мэт эрүүл хоол ид.|I enjoy sports ___ as tennis.|such~so~like
|Some fruits, ___ example oranges, have vitamin C.|for~as~by
|We visited cities ___ Paris and Rome.|like~as~such
b1|like ба as|like — «... шиг» (адилтгах): She sings like a bird. as — «... -ын хувьд, ... болж» (жинхэнэ үүрэг): She works as a teacher.¶as + өгүүлбэр: Do as I say.|like + N (шиг) · as + N (үүрэг) · as + S + V|She works as a nurse.|Тэр сувилагчаар ажилладаг.|He runs like the wind.|Тэр салхи шиг гүйдэг.|Do as I say.|Миний хэлснээр хий.|It looks like rain.|Бороо орох бололтой.|She works ___ a nurse.|as~like~such
|He runs ___ the wind.|like~as~such as
|Do ___ I say.|as~like~same
b1|always + Present Continuous: залхаах зуршил|always + Present Continuous нь уурлуулсан, залхаасан давтагдах зуршлыг илэрхийлнэ: He's always losing his keys! You're always complaining.|am / is / are + always + V-ing (гомдол)|He's always losing his keys!|Тэр түлхүүрээ байнга л гээдэг!|You're always complaining.|Чи дандаа л гомдоллодог.|She's always talking on the phone.|Тэр байнга утсаар ярьж байдаг.|My brother is always borrowing my things.|Ах маань миний юмыг байнга зээлдэг.|He's always ___ his keys!|losing~lose~loses|You're always ___.|complaining~complain~complained
|She's ___ talking on the phone.|always~ever~never
b1|Hurry up or ...: тушаал + or / and|Тушаал + or — «эс тэгвэл»: Hurry up or you'll be late. Тушаал + and — «тэгвэл»: Study hard and you'll pass.|Imperative + or + will (эс тэгвэл) · Imperative + and + will (тэгвэл)|Hurry up or you'll miss the bus.|Яар, эс тэгвэл автобуснаас хоцорно.|Study hard and you'll pass.|Сайн хичээ, тэгвэл тэнцэнэ.|Be careful or you'll fall.|Болгоомжтой бай, эс тэгвэл унана.|Take a taxi and you'll be there in ten minutes.|Такси барь, тэгвэл арван минутад хүрнэ.|Hurry up ___ you'll miss the bus.|or~and~so|Study hard ___ you'll pass.|and~or~but
|Be careful or you'll ___.|fall~falling~to fall
b1|reason for, increase in: нэр үг + угтвар|Зарим нэр үг тодорхой угтвар шаарддаг: a reason for, an increase / rise in, a solution to, an answer to, a cause of, an effect on, a need for.|reason for · increase in · solution to · cause of · effect on · need for|What's the reason for the delay?|Саатлын шалтгаан юу вэ?|There has been an increase in prices.|Үнэ өссөн.|We need a solution to this problem.|Бидэнд энэ асуудлын шийдэл хэрэгтэй.|Smoking has a bad effect on health.|Тамхи эрүүл мэндэд муугаар нөлөөлдөг.|What's the reason ___ the delay?|for~of~to|We need a solution ___ this problem.|to~for~of|There has been an increase ___ prices.|in~of~on
b1|go to hospital ба go to the hospital|Байгууллагыг зориулалтаар нь ашиглахад the-гүй: go to hospital (өвчтөнөөр), go to school (сурагчаар), go to prison. Барилгад л очих бол the: I went to the school to see the teacher.¶Америк англид go to the hospital гэдэг.|go to hospital / school / prison / church (зориулалтаар) · go to the ... (барилга)|He was taken to hospital after the accident.|Ослын дараа түүнийг эмнэлэгт хүргэсэн.|My mother went to the school to talk to my teacher.|Ээж маань багштай ярихаар сургууль дээр очсон.|The children go to school by bus.|Хүүхдүүд сургууль руугаа автобусаар явдаг.|He was sent to prison for five years.|Түүнийг таван жил хорьсон.|He was taken to ___ after the accident. (өвчтөн)|hospital~the hospital~a hospital|My mother went to ___ to talk to my teacher. (барилга)|the school~school~a school|The children go to ___ by bus.|school~the school~a school
b1|be good at, succeed in: чадвар|Чадварыг илэрхийлэх: be good / bad at + N / V-ing, be skilled at, succeed in + V-ing, be capable of + V-ing.|be good at + V-ing · succeed in + V-ing · be capable of + V-ing|She's very good at drawing.|Тэр зурахдаа их сайн.|He succeeded in passing the exam.|Тэр шалгалтад амжилттай тэнцсэн.|I'm bad at remembering names.|Би нэр цээжлэхдээ муу.|She is capable of doing better.|Тэр илүү сайн хийх чадвартай.|She's very good ___ drawing.|at~in~for|He succeeded ___ passing the exam.|in~at~to|She is capable ___ doing better.|of~to~for
b1|Would you mind + -ing?|Эелдэгээр гуйх: Would you mind + V-ing? — «... өгөхгүй юу?»: Would you mind opening the window? Зөвшөөрөхдөө: No, not at all. / Of course not.¶Would you mind if I + Past? — зөвшөөрөл асуух.|Would you mind + V-ing? · Would you mind if I + Past? — Not at all|Would you mind opening the window?|Цонхоо онгойлгож өгөхгүй юу?|Would you mind waiting a moment?|Түр хүлээж болох уу?|Would you mind if I sat here?|Энд суувал болох уу?|Not at all. Go ahead.|Огт үгүй. Суугаарай.|Would you mind ___ the window?|opening~to open~open|Would you mind if I ___ here?|sat~sit~sitting|Would you mind waiting? — Not at ___.|all~alone~mind
b1|I can't stand, I don't mind|Дуртай, дургүйн зэрэг: I love > I enjoy > I don't mind (хамаагүй) > I don't like > I can't stand / I hate (тэвчиж чадахгүй). Бүгдийн дараа V-ing.|love · enjoy · don't mind · can't stand · hate + V-ing|I can't stand waiting in queues.|Би дараалалд зогсохыг тэвчиж чаддаггүй.|I don't mind working at weekends.|Амралтын өдөр ажиллах надад хамаагүй.|She hates getting up early.|Тэр эрт босохыг үзэн яддаг.|He really enjoys cooking.|Тэр хоол хийх их дуртай.|I can't stand ___ in queues.|waiting~to wait~wait|I don't ___ working at weekends. (хамаагүй)|mind~care~matter|She ___ getting up early. (үзэн яддаг)|hates~likes~minds
b1|since I was a child: since + Past Simple|since + өгүүлбэр (Past Simple) — эхэлсэн үйл явдал, гол өгүүлбэр Present Perfect: I've known her since we were at school.|Present Perfect + since + S + Past Simple|I've lived here since I was a child.|Би багаасаа энд амьдарч байна.|We've been friends since we met at university.|Бид их сургуульд танилцсанаасаа хойш найзууд.|She has changed a lot since she moved to the city.|Хот руу нүүснээсээ хойш тэр их өөрчлөгдсөн.|I haven't seen him since he left.|Түүнийг явснаас хойш би хараагүй.|I've lived here since I ___ a child.|was~am~have been|I haven't seen him since he ___.|left~has left~leaves|She ___ a lot since she moved to the city.|has changed~changed~changes
b1|How many times have you ...?|Одоог хүртэлх давтамжийг Present Perfect-ээр асууна: How many times have you been to China? — I've been there three times.¶Хугацаа дууссан бол Past Simple: How many times did you call him yesterday?|How many times have you + V3? — ... times|How many times have you been to China?|Чи Хятадад хэдэн удаа очсон бэ?|I've seen this film three times.|Би энэ киног гурван удаа үзсэн.|How many times has she called you today?|Тэр өнөөдөр чам руу хэдэн удаа залгасан бэ?|I've only been there once.|Би тэнд ганц л удаа очсон.|How many times ___ you been to China?|have~did~are|I've seen this film three ___.|times~time~once
|I've only been there ___.|once~one time ago~ones
b1|be allowed to|be allowed to + V — «... хийхийг зөвшөөрдөг»: We are allowed to use phones. Хориглох: aren't allowed to. Өнгөрсөн: was allowed to.|am / is / are (not) allowed to + V · was allowed to|Are we allowed to take photos here?|Энд зураг авахыг зөвшөөрдөг үү?|You aren't allowed to smoke inside.|Дотор тамхи татахыг хориглоно.|I wasn't allowed to watch TV as a child.|Хүүхэд байхад намайг зурагт үзэхийг зөвшөөрдөггүй байсан.|Students are allowed to use dictionaries.|Сурагчид толь бичиг ашиглахыг зөвшөөрнө.|You ___ allowed to smoke inside.|aren't~don't~haven't|Are we allowed ___ photos here?|to take~take~taking
|I ___ allowed to watch TV as a child.|wasn't~didn't~haven't
b1|definitely, probably: итгэлийн зэрэг|Итгэлийн зэрэг: definitely / certainly (гарцаагүй) > probably (магадгүй, ихэвчлэн) > possibly / maybe (магадгүй).¶Байрлал: will-ийн дараа, won't-ийн өмнө: I'll probably come. I probably won't come.|will definitely / probably + V · probably won't · maybe (эхэнд)|I'll definitely call you tomorrow.|Би маргааш гарцаагүй залгана.|She'll probably be late.|Тэр хоцрох байх.|I probably won't go.|Би явахгүй байх.|Maybe we can meet next week.|Магадгүй бид ирэх долоо хоногт уулзаж болох юм.|She'll ___ be late. (магадгүй)|probably~maybe~possible|I ___ won't go.|probably~definitely will~maybe will
|I'll ___ call you tomorrow. (гарцаагүй)|definitely~maybe~perhaps may
b1|luckily, unfortunately: өгүүлбэрийн дайвар|Өгүүлбэр бүхэлд нь үнэлэх дайвар эхэнд, таслалтай: Luckily, ... (азаар), Unfortunately, ... (харамсалтай нь), Surprisingly, ... (гайхалтай нь), Hopefully, ... (найдаж байна).|Luckily, · Unfortunately, · Surprisingly, · Hopefully, · Obviously,|Luckily, nobody was hurt.|Азаар хэн ч гэмтээгүй.|Unfortunately, the shop was closed.|Харамсалтай нь дэлгүүр хаалттай байлаа.|Surprisingly, the test was easy.|Гайхалтай нь шалгалт амархан байлаа.|Hopefully, we'll finish today.|Өнөөдөр дуусгана гэж найдаж байна.|___, nobody was hurt. (азаар)|Luckily~Unluckily~Lucky|___, the shop was closed. (харамсалтай нь)|Unfortunately~Fortunately~Unfortunate|___, we'll finish today. (найдаж байна)|Hopefully~Hopeful~Hoping
b1|I hope that, I'm sure that: that-өгүүлбэр|Бодол, мэдрэмжийн үйл үг / тэмдэг нэрийн дараа that + өгүүлбэр: I hope (that) you're well. I'm sure (that) she'll come. Ярианд that-ийг ихэвчлэн орхино.|think / hope / know / believe + (that) + S + V · I'm sure / afraid / glad + (that) ...|I hope you're feeling better.|Бие чинь сайжирсан гэж найдаж байна.|I'm sure she'll come.|Тэр ирнэ гэдэгт би итгэлтэй байна.|I'm afraid we're closed.|Уучлаарай, бид хаалттай.|I didn't know that you were here.|Чамайг энд байгааг би мэдээгүй.|I'm ___ she'll come. (итгэлтэй)|sure~hope~think of|I'm ___ we're closed. (уучлаарай)|afraid~scared~fear|I hope ___ feeling better.|you're~your~you
b1|It's likely that: магадлал|Магадлалыг: It's likely / unlikely that ..., S + be + likely to + V: It's likely to rain. He's unlikely to win.|It's (un)likely that ... · S + be (un)likely to + V|It's likely to rain tomorrow.|Маргааш бороо орох магадлалтай.|He's unlikely to win.|Тэр хожих магадлал бага.|It's likely that prices will rise.|Үнэ өсөх магадлалтай.|Are they likely to agree?|Тэд зөвшөөрөх магадлалтай юу?|It's likely ___ rain tomorrow.|to~that~for|He's ___ to win. (магадлал бага)|unlikely~not likely to~dislikely|It's likely ___ prices will rise.|that~to~for
b1|It depends (on)|It depends — «шалтгаална»: Are you coming? — It depends. depend on + N / wh-өгүүлбэр: It depends on the weather. It depends on how much it costs.|It depends · depend on + N · depend on + wh-|Are you coming tomorrow? — It depends.|Маргааш ирэх үү? — Шалтгаална.|It depends on the weather.|Цаг агаараас шалтгаална.|It depends on how much it costs.|Хэдэн төгрөг байхаас шалтгаална.|Children depend on their parents.|Хүүхдүүд эцэг эхээсээ хамаардаг.|It depends ___ the weather.|on~of~from|It depends on ___ it costs.|how much~how much does~what much
|Children depend ___ their parents.|on~from~of
b1|children ба kids: албан ба энгийн үг|Ярианы ба албан үг: kids / children, get / receive, buy / purchase, help / assist, ask / enquire, need / require, start / commence.¶Албан захидал, эссэд албан хувилбарыг сонго.|kids — children · get — receive · buy — purchase · help — assist · need — require|We received your letter. (албан)|Бид таны захидлыг хүлээн авлаа.|I got your message. (энгийн)|Би мессежийг чинь авсан.|Tickets can be purchased online.|Билетийг онлайнаар худалдан авч болно.|Please let us know if you require assistance.|Тусламж шаардлагатай бол бидэнд мэдэгдэнэ үү.|Tickets can be ___ online. (албан)|purchased~bought up~got|We ___ your letter. (албан)|received~got~took|Please let us know if you ___ assistance. (албан)|require~need up~want
b1|gonna, wanna, gotta: ярианы хэлбэр|Ярианд: going to → gonna, want to → wanna, have got to → gotta, kind of → kinda. Эдгээрийг зөвхөн дотно яриа, мессежид хэрэглэнэ, албан бичигт бичихгүй.|gonna = going to · wanna = want to · gotta = have got to · kinda = kind of|I'm gonna call you later. (= going to)|Би дараа чам руу залгана.|Do you wanna come? (= want to)|Ирмээр байна уу?|I gotta go now. (= have got to)|Би одоо явах хэрэгтэй.|It's kinda cold today. (= kind of)|Өнөөдөр жаахан хүйтэн байна.|gonna = ___|going to~got to~want to|wanna = ___|want to~going to~have to
|gotta = ___|have got to~going to~want to
b1|un-, dis-, im-: сөрөг угтвар|Тэмдэг нэр, үйл үгийг эсрэг утгатай болгох: un- (unhappy, unable), dis- (dislike, disagree), im- (b, m, p-ийн өмнө: impossible, impatient), in- (incorrect), il- (illegal), ir- (irregular).|un- · dis- · im- (p, m, b) · in- · il- (l) · ir- (r)|It's impossible to finish today.|Өнөөдөр дуусгах боломжгүй.|I disagree with you.|Би чамтай санал нийлэхгүй.|That answer is incorrect.|Тэр хариулт буруу.|Driving without a licence is illegal.|Үнэмлэхгүй жолоодох нь хууль бус.|It's ___ to finish today.|impossible~unpossible~dispossible|That's ___. (legal-ийн эсрэг)|illegal~unlegal~inlegal|I ___ with you.|disagree~unagree~inagree
b1|flat ба apartment: британи, америк англи|Британи — америк: flat — apartment, lift — elevator, holiday — vacation, autumn — fall, mobile — cell phone, underground — subway, biscuit — cookie.¶Бичиг: colour — color, centre — center, travelled — traveled.|flat / apartment · lift / elevator · holiday / vacation · colour / color|We live in a flat on the fifth floor. (BrE)|Бид тавдугаар давхрын байранд амьдардаг.|Let's take the elevator. (AmE)|Цахилгаан шатаар явъя.|We went on vacation to Hawaii. (AmE)|Бид Хавай руу амралтаар явсан.|My favourite colour is blue. (BrE)|Миний дуртай өнгө цэнхэр.|lift (BrE) = ___ (AmE)|elevator~escalator~stairs|holiday (BrE) = ___ (AmE)|vacation~vocation~break day|flat (BrE) = ___ (AmE)|apartment~department~flatment
b1|on Monday morning, in the morning|in the morning / afternoon / evening, гэхдээ тодорхой өдөртэй бол on: on Monday morning, on the evening of 5 May. at night.¶this / next / last / every-тэй угтваргүй: this morning, every evening.|in the morning · on Monday morning · at night · this / every morning (угтваргүй)|I usually study in the evening.|Би ихэвчлэн орой хичээлээ хийдэг.|We have a meeting on Monday morning.|Бид даваа гарагийн өглөө хуралтай.|I can't sleep at night.|Би шөнө унтаж чадахгүй байна.|I saw her this morning.|Би түүнийг өнөө өглөө харсан.|We have a meeting ___ Monday morning.|on~in~at|I usually study ___ the evening.|in~on~at|I saw her ___ morning.|this~in this~on this
b1|friendly, lovely: -ly тэмдэг нэр|Зарим -ly-гээр төгссөн үг дайвар биш, тэмдэг нэр: friendly, lovely, lonely, silly, lively, elderly, likely.¶Тэдгээрээс дайвар хийхгүй: in a friendly way (friendlily биш).|friendly · lovely · lonely · silly · lively (тэмдэг нэр) · in a friendly way|She is very friendly.|Тэр их найрсаг.|What a lovely day!|Ямар сайхан өдөр вэ!|He felt lonely in the big city.|Тэр том хотод ганцаардаж байв.|He spoke to me in a friendly way.|Тэр надтай найрсагаар ярьсан.|He spoke to me ___.|in a friendly way~friendlily~friendly way
|She is very ___.|friendly~friend~friendlily|He felt ___ in the big city.|lonely~lonelily~alone lonely
b1|You're kidding! No way!: гайхал илэрхийлэх|Гайхал, үл итгэлийг ярианд: Really? / You're kidding! / No way! / I can't believe it! / Seriously? / What a surprise!|Really? · You're kidding! · No way! · I can't believe it! · Seriously?|I won the lottery! — You're kidding!|Би сугалаанд хожлоо! — Тоглож байгаа биз дээ!|She's quitting her job. — No way!|Тэр ажлаасаа гарах гэж байна. — Байж боломгүй!|I can't believe it! We won!|Итгэж чадахгүй нь! Бид хожлоо!|He's moving to Canada. — Seriously?|Тэр Канад руу нүүх гэж байна. — Үнэхээр үү?|I won the lottery! — You're ___!|kidding~joking me~laughing|I can't ___ it! We won!|believe~trust~think|She's quitting her job. — No ___!|way~how~what
b1|Could you explain ...?: тайлбар асуух|Ойлгоогүй зүйлээ тодруулах: Could you explain what ... means? Sorry, I didn't catch that. Could you say that again? Sorry, did you say ...?|Could you explain ...? · Sorry, I didn't catch that · Did you say ...?|Could you explain what this word means?|Энэ үг юу гэсэн утгатайг тайлбарлаж өгөхгүй юу?|Sorry, I didn't catch that.|Уучлаарай, би сайн сонссонгүй.|Sorry, did you say fifteen or fifty?|Уучлаарай, арван тав уу, тавь гэсэн үү?|Could you give me an example?|Жишээ хэлж өгөхгүй юу?|Sorry, I didn't ___ that.|catch~take~hold|Could you explain what this word ___?|means~mean~meaning|Could you ___ me an example?|give~say~tell to
b1|a number of ба the number of|a number of + олон тоо — «хэд хэдэн, олон» (олон тоот үйл үг): A number of students are absent. the number of — «... -ын тоо» (ганц тоот үйл үг): The number of students is growing.|a number of + N(pl) + are · the number of + N(pl) + is|A number of people were injured.|Хэд хэдэн хүн гэмтсэн.|The number of tourists is increasing.|Жуулчдын тоо нэмэгдэж байна.|A number of problems have appeared.|Хэд хэдэн асуудал гарч ирсэн.|The number of cars in the city is huge.|Хотын машины тоо асар их.|A number of people ___ injured.|were~was~is|The number of tourists ___ increasing.|is~are~were
|___ number of cars in the city is huge.|The~A~One
b1|one of the + олон тоо|one of the + олон тоот нэр үг — «... -ын нэг», ганц тоот үйл үгтэй: One of my friends lives in Korea. It's one of the best books.|one of the + N(pl) + ганц тоот V · one of the best + N(pl)|One of my friends lives in Korea.|Миний нэг найз Солонгост амьдардаг.|It's one of the best books I've read.|Энэ бол миний уншсан хамгийн сайн номнуудын нэг.|One of the windows is broken.|Цонхнуудын нэг нь хагарсан.|She is one of the most famous singers.|Тэр хамгийн алдартай дуучдын нэг.|One of my friends ___ in Korea.|lives~live~living|It's one of the best ___.|books~book~book's|One of the windows ___ broken.|is~are~were
b1|is used for + -ing: зориулалт|be used for + V-ing / be used to + V — «... -д хэрэглэгддэг (зориулалт)»: This knife is used for cutting bread. = is used to cut bread.¶be used to + V-ing (дассан)-тай андуурахгүй.|be used for + V-ing · be used to + V (зориулалт)|This knife is used for cutting bread.|Энэ хутгыг талх зүсэхэд хэрэглэдэг.|Computers are used to store information.|Компьютерийг мэдээлэл хадгалахад ашигладаг.|What is this tool used for?|Энэ багаж юунд хэрэглэгддэг вэ?|Salt is used for preserving meat.|Давсыг мах хадгалахад хэрэглэдэг.|This knife is used for ___ bread.|cutting~cut~to cut|Computers are used to ___ information.|store~storing~stored
|What is this tool used ___?|for~to~at
b1|What do you think of ...?: санал асуух|Санал бодол асуух: What do you think of / about ...? How do you feel about ...? What's your opinion of ...? Хариулт: I think it's ...|What do you think of / about ...? · How do you feel about ...? · What's your opinion of ...?|What do you think of the new teacher?|Шинэ багшийг ямар гэж бодож байна?|How do you feel about working from home?|Гэрээсээ ажиллах талаар юу гэж бодож байна?|What's your opinion of the film?|Киноны талаар ямар бодолтой байна?|I think it's a great idea.|Би гайхалтай санаа гэж бодож байна.|What do you think ___ the new teacher?|of~for~on|How do you ___ about working from home?|feel~think~say
|What's your ___ of the film?|opinion~think~idea to
`]);
