(window.LP=window.LP||[]).push(["fr",1,`
a1|Хүйс ба тодотгол үг: le, la, un, une|Франц хэлэнд нэр үг бүр эр (masculin) эсвэл эм (féminin) хүйстэй. Хүйсийг үгтэй нь хамт цээжил.¶Тодорхой: le (эр), la (эм), l' (эгшгийн өмнө), les (олон тоо). Тодорхой бус: un (эр), une (эм), des (олон тоо).|le livre · la maison · l'ami · les amis · un chat · une pomme · des fleurs|Le chat est noir.|Муур хар.|J'ai une sœur.|Би нэг эгчтэй.|Les enfants jouent.|Хүүхдүүд тоглож байна.|C'est un livre intéressant.|Энэ сонирхолтой ном.|___ maison est grande.|La~Le~Les|J'ai ___ chien. (нэг)|un~une~des|___ hôtel est près d'ici.|L'~La~Le
a1|être ба avoir|être (байх) ба avoir (эзэмших, -тай байх) нь хамгийн чухал хоёр үйл үг. Нас хэлэхэд avoir хэрэглэнэ: J'ai vingt ans — Би хорин настай.¶être: je suis, tu es, il/elle est, nous sommes, vous êtes, ils sont. avoir: j'ai, tu as, il a, nous avons, vous avez, ils ont.|je suis · tu es · il est · nous sommes · j'ai · tu as · il a · nous avons|Je suis mongol.|Би монгол хүн.|Tu as un frère ?|Чи ахтай юу?|Nous sommes étudiants.|Бид оюутнууд.|Elle a vingt ans.|Тэр хорин настай.|Je ___ fatigué.|suis~ai~es|Il ___ deux enfants.|a~est~as|Vous ___ français ?|êtes~avez~sont
a1|-er үйл үг: одоо цаг|Ихэнх франц үйл үг -er-ээр төгсдөг (parler, aimer, habiter). -er-ийг авч төгсгөл залгана.¶je -e, tu -es, il -e, nous -ons, vous -ez, ils -ent. -e, -es, -ent дуудагддаггүй: je parle, tu parles, ils parlent — бүгд «парль».|je parle · tu parles · il parle · nous parlons · vous parlez · ils parlent|J'aime le chocolat.|Би шоколадад дуртай.|Tu parles français ?|Чи франц хэлээр ярьдаг уу?|Nous habitons à Paris.|Бид Парист амьдардаг.|Ils regardent un film.|Тэд кино үзэж байна.|Nous ___ le français. (étudier)|étudions~étudiez~étudient|Vous ___ où ? (habiter)|habitez~habitons~habite|Elle ___ la musique. (aimer)|aime~aimes~aimons
a1|Үгүйсгэл: ne ... pas|Үгүйсгэхдээ үйл үгийг ne ... pas-аар хүрээлнэ. Эгшгийн өмнө ne нь n' болно: Je n'aime pas.¶Ярианд ne-г ихэвчлэн орхидог: Je sais pas. Тодотгол үг un/une/des үгүйсгэлд de болно: Je n'ai pas de voiture.|je ne parle pas · je n'aime pas · je n'ai pas de ...|Je ne comprends pas.|Би ойлгохгүй байна.|Il n'aime pas le café.|Тэр кофенд дургүй.|Nous n'avons pas de voiture.|Бидэнд машин алга.|Ce n'est pas difficile.|Энэ хэцүү биш.|Je ___ parle pas anglais.|ne~n'~pas|Elle n'a pas ___ frère.|de~un~le|Ce ___ pas cher.|n'est~ne est~est
a1|Асуулт асуух|Асуултыг гурван янзаар бүтээнэ: 1) өгүүлбэрийн аяыг өсгөх (Tu viens ?), 2) Est-ce que нэмэх (Est-ce que tu viens ?), 3) үйл үг, төлөөний үгийг солих (Viens-tu ?).¶Асуух үгс: où (хаана), quand (хэзээ), comment (яаж), pourquoi (яагаад), qu'est-ce que (юу).|Tu viens ? · Est-ce que tu viens ? · Où est-ce que tu habites ?|Est-ce que tu as faim ?|Чи өлсөж байна уу?|Où est la gare ?|Буудал хаана вэ?|Qu'est-ce que tu fais ?|Чи юу хийж байна?|Comment tu t'appelles ?|Чамайг хэн гэдэг вэ?|___ est-ce que tu habites ? (хаана)|Où~Quand~Qui|___ que tu manges ? (юу)|Qu'est-ce~Est-ce~Où est-ce|___ ça va ? (яаж)|Comment~Pourquoi~Quand
a2|Passé composé: өнгөрсөн цаг|Болж өнгөрсөн үйл: avoir (эсвэл être) + үйл үгийн дагавар хэлбэр. -er үйл үг → -é: parler → parlé.¶Хөдөлгөөний үйл үгс (aller, venir, partir, arriver...) être-тэй ордог бөгөөд хүйс, тоогоороо зохицно: elle est allée.|j'ai mangé · tu as parlé · il a fini · je suis allé · elle est allée|Hier, j'ai mangé une pizza.|Өчигдөр би пицца идсэн.|Tu as vu ce film ?|Чи тэр киног үзсэн үү?|Nous sommes allés à la mer.|Бид далайд очсон.|Elle est arrivée à midi.|Тэр үд дунд ирсэн.|J'___ regardé la télé.|ai~suis~as|Ils ___ partis hier.|sont~ont~a|Elle est ___ en France. (aller)|allée~allé~aller
a2|Ойрын ирээдүй: aller + үйл үг|Удахгүй болох үйлийг aller (явах) + үйл үгийн үндсэн хэлбэрээр хэлнэ — англи хэлний going to шиг.¶aller: je vais, tu vas, il va, nous allons, vous allez, ils vont.|je vais manger · tu vas partir · nous allons voir|Je vais apprendre le français.|Би франц хэл сурна.|Il va pleuvoir.|Бороо орох гэж байна.|Nous allons voyager en été.|Бид зун аялна.|Qu'est-ce que tu vas faire demain ?|Маргааш чи юу хийх вэ?|Je ___ partir demain.|vais~vas~va|Nous ___ manger au restaurant.|allons~allez~vont|Ils ___ arriver ce soir.|vont~va~allons
a1|Тэмдэг нэрийн зохицол|Тэмдэг нэр нь нэр үгийнхээ хүйс, тоотой зохицно: эм хүйст -e, олон тоонд -s нэмнэ.¶Ихэнх тэмдэг нэр нэр үгийн дараа ордог: une voiture rouge. Гэхдээ зарим богино үг өмнө нь ордог: petit, grand, beau, bon, nouveau.|petit → petite → petits → petites · un livre intéressant|J'ai une petite maison.|Би жижиг байшинтай.|Elle porte une robe bleue.|Тэр цэнхэр даашинз өмссөн.|Mes amis sont contents.|Найзууд маань баяртай байна.|C'est une bonne idée.|Энэ сайн санаа.|Une voiture ___ (vert)|verte~vert~verts|Les livres sont ___ (intéressant)|intéressants~intéressante~intéressant|Ma sœur est ___ (grand)|grande~grand~grands
`]);
