(window.LP=window.LP||[]).push(["tr",1,`
a1|Эгшгийн зохицол ба олон тоо|Турк хэлэнд монгол хэлтэй адил эгшиг зохицох ёс бий: залгавар нь үгийн сүүлийн эгшгээс хамаарч өөрчлөгдөнө.¶Олон тоо: сүүлийн эгшиг a, ı, o, u бол -lar; e, i, ö, ü бол -ler. Тоо нэрийн дараа олон тоо хэрэглэхгүй: iki kedi (хоёр муур).|a, ı, o, u → -lar · e, i, ö, ü → -ler|Kediler süt içiyor.|Муурнууд сүү ууж байна.|Evler çok büyük.|Байшингууд их том.|Kitaplar masada.|Номнууд ширээн дээр байна.|Üç arkadaşım var.|Би гурван найзтай.|kitap → kitap___|lar~ler~lır|ev → ev___|ler~lar~lür|okul → okul___|lar~ler~lör
a1|Би ... байна: -(y)ım, -sın, -dır|Турк хэлэнд «байх» үйл үг тусдаа байдаггүй: нэр, тэмдэг нэрт хүний залгавар залгана.¶ben -(y)ım/im/um/üm, sen -sın/sin/sun/sün, o -(dır), biz -(y)ız, siz -sınız, onlar -lar. Эгшгээр төгссөн үгэнд «y» нэмнэ: öğrenci-y-im.|ben öğrenciyim · sen öğrencisin · o öğrenci(dir) · biz öğrenciyiz|Ben öğrenciyim.|Би оюутан.|Sen çok yorgunsun.|Чи их ядарсан байна.|O doktor.|Тэр эмч.|Biz Moğoluz.|Бид монголчууд.|Ben öğretmen___.|im~sin~ız|Sen mutlu___.|sun~um~uz|Biz hazır___.|ız~ım~sın
a1|Одоо цаг: -iyor|Яг одоо болж буй, эсвэл ойрын үйлийг -iyor-оор илэрхийлнэ. Үйл үгийн -mak/-mek-ийг авч -iyor (ı/i/u/ü эгшгийн зохицлоор) нэмээд хүний залгавар залгана.¶Эгшгээр төгссөн язгуурын сүүлийн эгшиг унана: oku-mak → okuyorum, bekle-mek → bekliyorum.|gel-mek → geliyorum · yap-mak → yapıyorum · oku-mak → okuyorum|Ben kitap okuyorum.|Би ном уншиж байна.|Sen ne yapıyorsun?|Чи юу хийж байна?|O televizyon izliyor.|Тэр зурагт үзэж байна.|Biz Türkçe öğreniyoruz.|Бид турк хэл сурч байна.|Ben şimdi çay iç___.|iyorum~iyorsun~iyoruz|Sen nereye gid___?|iyorsun~iyorum~iyor|Onlar futbol oyn___.|uyorlar~uyoruz~uyorum
a1|-de, -e, -den: хаана, хаашаа, хаанаас|Турк хэлний тийн ялгал монгол хэлтэй их төстэй.¶-de/-da/-te/-ta = -д, -т (хаана): evde — гэрт. -e/-a = руу, -д (хаашаа): eve — гэр рүү. -den/-dan/-ten/-tan = -аас (хаанаас): evden — гэрээс. ç, f, h, k, p, s, ş, t-ээр төгссөн үгэнд d нь t болно: parkta.|evde (гэрт) · eve (гэр рүү) · evden (гэрээс)|Ben evdeyim.|Би гэртээ байна.|Okula gidiyorum.|Би сургууль руу явж байна.|Moğolistan'dan geldim.|Би Монголоос ирсэн.|Çocuklar parkta oynuyor.|Хүүхдүүд цэцэрлэгт хүрээлэнд тоглож байна.|Kitap masa___. (ширээн дээр)|da~ya~dan|Yarın İstanbul'___ gidiyorum. (руу)|a~da~dan|Ben Ulanbator'___ geldim. (аас)|dan~da~a
a1|var ба yok: бий, байхгүй|var = бий, байна; yok = байхгүй, алга. Эзэмшлийг хамаатуулах залгавартай хамт хэлнэ: Benim kedim var — Би мууртай (миний муур бий).¶Асуулт: var mı? / yok mu?|... var · ... yok · ... var mı?|Benim bir kedim var.|Би нэг мууртай.|Bugün dersim yok.|Өнөөдөр надад хичээл алга.|Burada internet var mı?|Энд интернет байна уу?|Evde süt yok.|Гэрт сүү алга.|Param ___, alamam. (алга)|yok~var~mı|Sorunuz ___ mı? (бий юу)|var~yok~değil|Burada otobüs durağı ___. (бий)|var~yok~değil
a2|Өнгөрсөн цаг: -di|Болж өнгөрсөн, өөрөө мэдэх үйлийг -di/-dı/-du/-dü (хатуу гийгүүлэгчийн дараа -ti/-tı/-tu/-tü) залгавраар илэрхийлнэ.¶Хүний залгавар: -m (би), -n (чи), — (тэр), -k (бид), -nız (та нар), -ler (тэд).|gel-di-m (ирсэн) · yap-tı-n · git-ti · oku-du-k|Dün sinemaya gittim.|Өчигдөр би кино руу явсан.|Sen kahvaltı yaptın mı?|Чи өглөөний цайгаа уусан уу?|O geçen yıl Türkiye'ye geldi.|Тэр өнгөрсөн жил Турк руу ирсэн.|Biz çok güldük.|Бид их инээсэн.|Dün çok çalış___. (би)|tım~dım~tık|Biz yemek ye___. (бид)|dik~dim~din|Sen nereye git___? (чи)|tin~tim~tik
a2|Ирээдүй цаг: -ecek / -acak|Ирээдүйд болох үйл: -ecek/-acak + хүний залгавар. Эгшгээр төгссөн язгуурт y нэмнэ: oku-y-acağım. Хүний залгавар эгшгээр эхэлбэл k нь ğ болно: gideceğim.|gel-eceğ-im · yap-acak-sın · oku-y-acak|Yarın sana yazacağım.|Маргааш би чамд бичнэ.|Hafta sonu ne yapacaksın?|Амралтын өдөр чи юу хийх вэ?|Gelecek yıl İstanbul'a gideceğiz.|Ирэх жил бид Истанбул руу явна.|Akşam yağmur yağacak.|Орой бороо орно.|Yarın sinemaya git___. (би)|eceğim~ecek~eceksin|Ne zaman gel___? (чи)|eceksin~eceğim~ecekler|Onlar yarın oku___. (тэд)|yacaklar~yacağız~yacak
a2|Асуулт: mi, mı, mu, mü|Тийм/үгүй асуултыг mi/mı/mu/mü сул үгээр бүтээнэ — монголын «уу/үү» шиг. Энэ нь тусдаа бичигдэх ч эгшгийн зохицлоор өөрчлөгдөнө.¶Хүний залгавар нь mi-д залгагдана: Öğrenci misin? Гэхдээ -iyor-той: Geliyor musun?|güzel mi? · doğru mu? · büyük mü? · geliyor musun?|Türkçe biliyor musun?|Чи турк хэл мэдэх үү?|Bu kitap güzel mi?|Энэ ном гоё юу?|Sen öğrenci misin?|Чи оюутан уу?|Yarın okul var mı?|Маргааш хичээлтэй юу?|Kahve sıcak ___?|mı~mi~mu|Bu senin ev___ mi? (гэр чинь үү)|in~im~iniz|Doğru ___?|mu~mi~mü
`]);
