window.PLACE_MORE=window.PLACE_MORE||{};
window.PLACE_MORE.de=[
["a1","Er ___ Lehrer.",["ist","bist","bin"],0,"Тэр багш."],
["a1","Wir ___ Studenten.",["sind","ist","seid"],0,"Бид оюутнууд."],
["a1","Du ___ Deutsch.",["sprichst","spreche","sprechen"],0,"Чи герман хэлээр ярьдаг."],
["a1","Sie ___ in Berlin.",["wohnt","wohnst","wohne"],0,"Тэр Берлинд амьдардаг."],
["a1","Ich ___ einen Hund.",["habe","hat","hast"],0,"Надад нохой бий."],
["a1","Das ist ___ Tasche. (f)",["meine","mein","meinen"],0,"Энэ бол миний цүнх."],
["a1","___ Mann ist alt. (m)",["Der","Die","Das"],0,"Тэр эр настай."],
["a1","___ Frau ist nett. (f)",["Die","Der","Das"],0,"Тэр эмэгтэй сайхан сэтгэлтэй."],
["a1","Ich esse ___ Apfel. (m)",["einen","ein","eine"],0,"Би нэг алим иднэ."],
["a1","Wir gehen ___ Schule.",["zur","zum","im"],0,"Бид сургууль руу явна."],
["a1","Ich fahre ___ dem Bus.",["mit","bei","nach"],0,"Би автобусаар явдаг."],
["a1","Das Buch liegt ___ dem Tisch.",["auf","in","bei"],0,"Ном ширээн дээр байна."],
["a1","Wie ___ bist du?",["alt","viel","lang"],0,"Чи хэдтэй вэ?"],
["a1","Wo ___ du?",["wohnst","wohne","wohnt"],0,"Чи хаана амьдардаг вэ?"],
["a1","Ich ___ nicht gern Fisch.",["esse","isst","essen"],0,"Би загас идэх дургүй."],
["a1","Gestern ___ ich zu Hause.",["war","bin","wäre"],0,"Өчигдөр би гэртээ байсан."],
["a1","Das ist ___ Kind. (n, kein)",["kein","keine","keinen"],0,"Энэ хүүхэд биш."],
["a1","Ich habe ___ Zeit.",["keine","kein","nicht"],0,"Надад цаг алга."],
["a1","Es ___ heute kalt.",["ist","hat","wird gestern"],0,"Өнөөдөр хүйтэн байна."],
["a1","Der Zug fährt um ___ Uhr.",["acht","achte","achten"],0,"Галт тэрэг найман цагт явна."],
["a1","Sie ___ jeden Tag Tee.",["trinkt","trinken","trinke"],0,"Тэр өдөр бүр цай уудаг."],
["a1","Ich möchte ___ Kaffee.",["einen","ein","eine"],0,"Би кофе авмаар байна."],
["a1","Kannst du mir ___?",["helfen","hilfst","hilft"],0,"Чи надад тусалж чадах уу?"],
["a1","Hier ___ es viele Bücher.",["gibt","ist","hat"],0,"Энд олон ном бий."],
["a1","Ich komme ___ der Mongolei.",["aus","von","nach"],0,"Би Монголоос ирсэн."],
["a1","Die Katze ist ___ dem Bett.",["unter","zu","für"],0,"Муур орны доор байна."],
["a1","Mein Bruder ist ___ als ich.",["älter","alt","ältesten"],0,"Миний ах надаас том."],
["adv","Er sagt, dass er müde ___.",["ist","sei bin","bist"],0,"Тэр ядарсан гэж хэлж байна."],
["adv","Ich weiß nicht, ___ er kommt.",["ob","wenn","dass"],0,"Тэр ирэх эсэхийг би мэдэхгүй."],
["adv","Wenn ich Zeit ___, würde ich kommen.",["hätte","habe","hatte"],0,"Хэрэв цаг байсан бол би ирэх байсан."],
["adv","Ich habe gestern einen Film ___.",["gesehen","sehen","sah"],0,"Би өчигдөр кино үзсэн."],
["adv","Das Haus wurde 1990 ___.",["gebaut","bauen","baute"],0,"Байшинг 1990 онд барьсан."],
["adv","Sie fragt, ___ ich wohne.",["wo","wann","wer"],0,"Тэр надаас хаана амьдардгийг асууж байна."],
["adv","Er arbeitet, ___ Geld zu verdienen.",["um","dass","weil"],0,"Тэр мөнгө олохын тулд ажилладаг."],
["adv","Ich freue mich ___ die Reise.",["auf","über","von"],0,"Би аяллыг хүлээж байна."],
["adv","Sie interessiert sich ___ Musik.",["für","an","zu"],0,"Тэр хөгжимд сонирхолтой."],
["adv","Ich warte ___ den Bus.",["auf","an","um"],0,"Би автобус хүлээж байна."],
["adv","Er hat Angst ___ Hunden.",["vor","von","für"],0,"Тэр нохойноос айдаг."],
["adv","Das ist der Mann, ___ ich gestern getroffen habe.",["den","der","dem"],0,"Энэ бол миний өчигдөр уулзсан эр."],
["adv","Die Frau, ___ dort steht, ist meine Lehrerin.",["die","der","den"],0,"Тэнд зогсож байгаа эмэгтэй бол миний багш."],
["adv","___ es regnet, bleibe ich zu Hause.",["Weil","Denn","Deshalb"],0,"Бороо орж байгаа учир би гэртээ байна."],
["adv","Obwohl er müde war, ___ er weiter.",["arbeitete","er arbeitete","arbeiten"],0,"Тэр ядарсан байсан ч үргэлжлүүлэн ажилласан."],
["adv","Ich habe keine Lust, ___ Hause zu bleiben.",["zu","um","dass"],0,"Би гэртээ үлдэх хүсэлгүй байна."],
["adv","Sie hat mir ein Buch ___.",["geschenkt","schenken","schenkte"],0,"Тэр надад ном бэлэглэсэн."],
["adv","Nach dem Essen ___ wir spazieren.",["gehen","geht","gingen wir hat"],0,"Хоолны дараа бид зугаалахаар явна."],
["adv","Er ist ___ als sein Bruder.",["fleißiger","fleißig","am fleißigsten"],0,"Тэр ахаасаа илүү хичээнгүй."],
["adv","Das ist der ___ Film, den ich gesehen habe.",["beste","gute","besser"],0,"Энэ бол миний үзсэн хамгийн сайн кино."],
["adv","Er wird morgen ___.",["kommen","gekommen","kam"],0,"Тэр маргааш ирэх болно."],
["adv","Ich muss noch ___.",["arbeiten","arbeitet","gearbeitet zu"],0,"Би дахиад ажиллах хэрэгтэй."],
["adv","Er hat sich ___ verändert.",["stark","stärker als","starken"],0,"Тэр маш их өөрчлөгдсөн."],
["adv","Wir haben uns lange nicht ___.",["gesehen","sehen","sah"],0,"Бид удаан уулзаагүй."],
["adv","Das Buch, ___ ich lese, ist spannend.",["das","dem","der"],0,"Миний уншиж буй ном сонирхолтой."],
["adv","Man sollte ___ Umwelt schützen.",["die","der","das"],0,"Байгаль орчноо хамгаалах хэрэгтэй."],
["adv","Er tut so, ___ ob er nichts wüsste.",["als","wie","dass"],0,"Тэр юу ч мэдэхгүй юм шиг дүр эсгэнэ."],
["adv","Bevor ich gehe, ___ ich dich an.",["rufe","rufst","gerufen"],0,"Явахаасаа өмнө би чамд залгана."],
["adv","Je mehr du übst, ___ besser wirst du.",["desto","umso als","wie"],0,"Хичээллэх тусам сайжирна."]
];
