/* Түвшин тогтоох тестийн нэмэлт асуултууд: [түвшин, асуулт, сонголтууд, зөв хариултын индекс, Монгол орчуулга] */
window.PLACE_MORE=window.PLACE_MORE||{};
window.PLACE_MORE.en=[
["a1","I ___ a student.",["am","is","are"],0,"Би оюутан."],
["a1","They ___ happy.",["are","is","am"],0,"Тэд баяртай."],
["a1","My mother ___ a teacher.",["is","are","am"],0,"Миний ээж багш."],
["a1","She ___ tea every day.",["drinks","drink","drinking"],0,"Тэр өдөр бүр цай уудаг."],
["a1","We ___ football on Sunday.",["play","plays","playing"],0,"Бид ням гаригт хөлбөмбөг тоглодог."],
["a1","___ you like coffee?",["Do","Does","Is"],0,"Та кофед дуртай юу?"],
["a1","He ___ not like fish.",["does","do","is"],0,"Тэр загаснд дургүй."],
["a1","There is ___ apple on the table.",["an","a","two"],0,"Ширээн дээр нэг алим байна."],
["a1","I have two ___.",["brothers","brother","a brothers"],0,"Надад хоёр ах/дүү бий."],
["a1","She has ___ umbrella.",["an","a","many"],0,"Түүнд нэг шүхэр бий."],
["a1","Where ___ you from?",["are","is","am"],0,"Та хаанаас ирсэн бэ?"],
["a1","What time ___ it?",["is","are","am"],0,"Хэдэн цаг болж байна вэ?"],
["a1","I ___ up at seven.",["get","gets","getting"],0,"Би долоон цагт босдог."],
["a1","The book is ___ the table.",["on","in","at"],0,"Ном ширээн дээр байна."],
["a1","I go to school ___ bus.",["by","with","at"],0,"Би сургуульд автобусаар явдаг."],
["a1","He is ___ than his brother.",["taller","tall","tallest"],0,"Тэр ахаасаа өндөр."],
["a1","___ is your name?",["What","Who","Where"],0,"Таны нэр хэн бэ?"],
["a1","How ___ apples do you have?",["many","much","long"],0,"Танд хэдэн алим байна?"],
["a1","I ___ TV now.",["am watching","watch","watched"],0,"Би одоо зурагт үзэж байна."],
["a1","Yesterday I ___ to the market.",["went","go","going"],0,"Өчигдөр би зах руу явсан."],
["a1","She can ___ English.",["speak","speaks","speaking"],0,"Тэр англиар ярьж чадна."],
["a1","Please ___ the door.",["close","closes","closing"],0,"Хаалгаа хаана уу."],
["a1","My birthday is ___ May.",["in","on","at"],0,"Миний төрсөн өдөр тавдугаар сард."],
["a1","We have breakfast ___ eight o'clock.",["at","in","on"],0,"Бид найман цагт өглөөний цай уудаг."],
["a1","I have ___ money.",["no","not","none"],0,"Надад мөнгө алга."],
["a1","Those ___ my friends.",["are","is","am"],0,"Тэд миний найзууд."],
["a1","This bag is ___ than that one.",["cheaper","cheap","cheapest"],0,"Энэ цүнх тэрнээс хямд."],
["a1","___ a nice day!",["What","How","Which"],0,"Ямар сайхан өдөр вэ!"],
["adv","If I ___ you, I would go.",["were","am","will be"],0,"Хэрэв би чи байсан бол явах байсан."],
["adv","She has lived here ___ 2015.",["since","for","from"],0,"Тэр 2015 оноос хойш энд амьдарч байна."],
["adv","I have known him ___ ten years.",["for","since","from"],0,"Би түүнийг арван жил мэднэ."],
["adv","The book ___ by millions.",["was read","read","reads"],0,"Номыг сая сая хүн уншсан."],
["adv","He told me he ___ the next day.",["would come","will come","comes"],0,"Тэр надад маргааш нь ирнэ гэж хэлсэн."],
["adv","By the time we arrived, the film ___.",["had started","started","has started"],0,"Бид ирэх үед кино аль хэдийн эхэлсэн байсан."],
["adv","I wish I ___ more time.",["had","have","will have"],0,"Илүү их цагтай байсан бол гэж боддог."],
["adv","She suggested ___ a taxi.",["taking","to taking","take"],0,"Тэр такси барихыг санал болгосон."],
["adv","I look forward to ___ you.",["seeing","see","saw"],0,"Би чамтай уулзахыг хүлээж байна."],
["adv","He is used to ___ early.",["getting up","get up","got up"],0,"Тэр эрт босч сурсан."],
["adv","The more you practice, ___ you get.",["the better","better","the best"],0,"Хичээллэх тусам сайжирна."],
["adv","You ___ smoke here. It is forbidden.",["mustn't","don't have to","needn't"],0,"Энд тамхи татаж болохгүй. Хориотой."],
["adv","I ___ him yesterday, but he was out.",["called","have called","call"],0,"Би өчигдөр түүнд залгасан ч тэр гадаа байсан."],
["adv","If it rains tomorrow, we ___ at home.",["will stay","would stay","stayed"],0,"Хэрэв маргааш бороо орвол бид гэртээ үлдэнэ."],
["adv","She is the person ___ helped me.",["who","which","whose"],0,"Тэр бол надад тусалсан хүн."],
["adv","This is the house ___ I was born.",["where","who","whom"],0,"Энэ бол миний төрсөн байшин."],
["adv","He apologized ___ being late.",["for","of","to"],0,"Тэр хоцорсондоо уучлал гуйсан."],
["adv","I am interested ___ music.",["in","on","at"],0,"Би хөгжимд сонирхолтой."],
["adv","She is good ___ math.",["at","in","on"],0,"Тэр математикт сайн."],
["adv","___ the rain, we went out.",["Despite","Although","Because"],0,"Бороо орсон ч бид гарсан."],
["adv","He must ___ home; the lights are on.",["be","is","being"],0,"Тэр гэртээ байгаа байх; гэрэл асаалттай байна."],
["adv","I ___ TV when the phone rang.",["was watching","watched","watch"],0,"Утас дуугарах үед би зурагт үзэж байсан."],
["adv","She asked me ___ I lived.",["where","that","what"],0,"Тэр надаас хаана амьдардгийг асуусан."],
["adv","The teacher made us ___ the text again.",["read","to read","reading"],0,"Багш биднийг текстийг дахин уншуулсан."],
["adv","I would rather ___ home tonight.",["stay","to stay","staying"],0,"Би өнөө орой гэртээ үлдсэн нь дээр."],
["adv","We ran out ___ milk.",["of","from","with"],0,"Бидний сүү дууссан."],
["adv","Please let me ___ if you need help.",["know","to know","knowing"],0,"Тусламж хэрэгтэй бол надад мэдэгдээрэй."]
];
